import { defineDiagnostics } from "nostics"

const dynamicError = {
  why: ({ message }: { message?: unknown }) => message === undefined ? "" : String(message),
}

// Each code identifies one ViteHub failure site. Keep published codes stable.
export const workflowErrorDiagnostics = /*#__PURE__*/ defineDiagnostics({
  docsBase: () => "https://vitehub.dev/docs/reference/errors-diagnostics",
  codes: {
    WORKFLOW_C0001: dynamicError,
    WORKFLOW_C0002: dynamicError,
    WORKFLOW_C0003: dynamicError,
    WORKFLOW_C0004: dynamicError,
    WORKFLOW_C0005: dynamicError,
    WORKFLOW_C0006: dynamicError,
    WORKFLOW_C0007: dynamicError,
    WORKFLOW_C0008: dynamicError,
    WORKFLOW_C0009: dynamicError,
    WORKFLOW_C0010: dynamicError,
    WORKFLOW_C0011: dynamicError,
    WORKFLOW_C0012: dynamicError,
    WORKFLOW_C0013: dynamicError,
    WORKFLOW_C0014: dynamicError,
    WORKFLOW_C0015: dynamicError,
    WORKFLOW_C0016: dynamicError,
    WORKFLOW_R0001: dynamicError,
    WORKFLOW_R0002: dynamicError,
    WORKFLOW_R0003: dynamicError,
    WORKFLOW_R0004: dynamicError,
    WORKFLOW_R0005: dynamicError,
    WORKFLOW_R0006: dynamicError,
    WORKFLOW_R0007: dynamicError,
    WORKFLOW_R0008: dynamicError,
    WORKFLOW_R0009: dynamicError,
    WORKFLOW_R0010: dynamicError,
    WORKFLOW_R0011: dynamicError,
    WORKFLOW_R0012: dynamicError,
    WORKFLOW_R0013: dynamicError,
    WORKFLOW_R0014: dynamicError,
    WORKFLOW_R0015: dynamicError,
    WORKFLOW_R0016: dynamicError,
    WORKFLOW_R0017: dynamicError,
    WORKFLOW_R0018: dynamicError,
    WORKFLOW_R0019: dynamicError,
    WORKFLOW_R0020: dynamicError,
    WORKFLOW_R0021: dynamicError,
    WORKFLOW_R0022: dynamicError,
    WORKFLOW_R0023: dynamicError,
    WORKFLOW_R0024: dynamicError,
    WORKFLOW_R0025: dynamicError,
    WORKFLOW_R0026: dynamicError,
    WORKFLOW_B0001: dynamicError,
  },
})
