version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
      - /.github/actions/setup
      - /.github/actions/setup-deno
    schedule:
      interval: weekly
    groups:
      github-actions:
        patterns:
          - "*"
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    allow:
      - dependency-name: pkg-pr-new
      - dependency-name: wrangler
    groups:
      ci-executables:
        patterns:
          - pkg-pr-new
          - wrangler
