name: Setup
description: Install Vite+ and project dependencies
runs:
  using: composite
  steps:
    - uses: voidzero-dev/setup-vp@1b32467adbe183473499fd9d5d372c3ed9641754 # v1.18.0
      with:
        node-version: "24"
        cache: true

    - name: Install dependencies
      shell: bash
      run: vp install --frozen-lockfile
