name: Setup
description: Install Vite+ and project dependencies
runs:
  using: composite
  steps:
    - uses: voidzero-dev/setup-vp@250f29ce396baf5e8f24498e17c0dfdebabc26eb # v1.15.0
      with:
        node-version: "24"
        cache: true

    - name: Install dependencies
      shell: bash
      run: vp install --frozen-lockfile
