import { defineDiagnostics } from "nostics"

const dynamicError = {
  why: ({ message }: { message?: unknown }) => message === undefined ? "" : String(message),
}

// Each code identifies one ViteHub failure site. Keep published codes stable.
export const scheduleErrorDiagnostics = /*#__PURE__*/ defineDiagnostics({
  docsBase: () => "https://vitehub.dev/docs/reference/errors-diagnostics",
  codes: {
    SCHEDULE_C0001: dynamicError,
    SCHEDULE_C0002: dynamicError,
    SCHEDULE_C0003: dynamicError,
    SCHEDULE_C0004: dynamicError,
    SCHEDULE_C0005: dynamicError,
    SCHEDULE_C0006: dynamicError,
    SCHEDULE_C0007: dynamicError,
    SCHEDULE_C0008: dynamicError,
    SCHEDULE_C0009: dynamicError,
    SCHEDULE_R0001: dynamicError,
    SCHEDULE_R0002: dynamicError,
    SCHEDULE_R0003: dynamicError,
    SCHEDULE_R0004: dynamicError,
    SCHEDULE_R0005: dynamicError,
    SCHEDULE_R0006: dynamicError,
    SCHEDULE_R0007: dynamicError,
    SCHEDULE_R0008: dynamicError,
    SCHEDULE_R0009: dynamicError,
    SCHEDULE_R0010: dynamicError,
    SCHEDULE_R0011: dynamicError,
    SCHEDULE_R0012: dynamicError,
    SCHEDULE_R0013: dynamicError,
    SCHEDULE_R0014: dynamicError,
    SCHEDULE_R0015: dynamicError,
    SCHEDULE_R0016: dynamicError,
    SCHEDULE_R0017: dynamicError,
    SCHEDULE_R0018: dynamicError,
    SCHEDULE_R0019: dynamicError,
    SCHEDULE_R0020: dynamicError,
    SCHEDULE_R0021: dynamicError,
    SCHEDULE_R0022: dynamicError,
    SCHEDULE_R0023: dynamicError,
    SCHEDULE_R0024: dynamicError,
    SCHEDULE_R0025: dynamicError,
    SCHEDULE_R0026: dynamicError,
    SCHEDULE_R0027: dynamicError,
    SCHEDULE_R0028: dynamicError,
    SCHEDULE_R0029: dynamicError,
    SCHEDULE_R0030: dynamicError,
    SCHEDULE_R0031: dynamicError,
    SCHEDULE_R0032: dynamicError,
    SCHEDULE_R0033: dynamicError,
    SCHEDULE_R0034: dynamicError,
    SCHEDULE_R0035: dynamicError,
    SCHEDULE_B0001: dynamicError,
    SCHEDULE_B0002: dynamicError,
    SCHEDULE_B0003: dynamicError,
    SCHEDULE_B0004: dynamicError,
    SCHEDULE_B0005: dynamicError,
  },
})
