packages:
  - "docs"
  - "playground/*"
  - "packages/*"
  - "packages/*/examples/*"
  - "packages/*/playground/*"
catalog:
  '@cloudflare/sandbox': ^0.8.11
  '@comark/vue': ^0.3.1
  '@iconify-json/lucide': ^1.2.105
  '@libsql/client': ^0.15.15
  '@nuxt/content': ^3.13.0
  '@nuxt/kit': ^4.4.2
  '@nuxt/schema': ^4.4.2
  '@oku-ui/motion': ^0.4.3
  '@types/node': ^25.6.0
  '@upstash/redis': ^1.37.0
  '@valibot/to-json-schema': ^1.6.0
  '@vercel/blob': ^2.3.3
  '@vercel/functions': ^3.4.3
  '@vercel/queue': ^0.0.0-alpha.23
  '@vercel/sandbox': ^1.10.0
  '@vitejs/devtools': https://pkg.pr.new/vitejs/devtools/@vitejs/devtools@307
  '@vitejs/devtools-kit': https://pkg.pr.new/vitejs/devtools/@vitejs/devtools-kit@307
  '@vueuse/core': ^14.2.1
  '@vueuse/nuxt': ^14.2.1
  async-retry: ^1.3.3
  better-sqlite3: ^12.9.0
  chat: ^4.27.0
  chat-state-cloudflare-do: ^0.2.0
  comark: ^0.3.2
  consola: ^3.4.2
  defu: ^6.1.4
  docus: ^5.9.0
  drizzle-orm: ^0.44.7
  esbuild: ^0.28.0
  exsolve: ^1.0.8
  files-sdk: ^1.2.0
  get-port-please: ^3.2.0
  h3: 2.0.1-rc.20
  hookable: ^6.1.1
  local-pkg: ^1.1.2
  mlly: ^1.8.1
  motion-v: ^2.2.1
  mrmime: ^2.0.1
  nitro: 3.0.260311-beta
  nuxt: ^4.4.2
  ofetch: ^1.5.1
  openworkflow: ^0.9.0
  oxlint: ^1.60.0
  pathe: ^2.0.3
  picocolors: ^1.1.1
  pkg-types: ^2.3.0
  postgres: ^3.4.9
  rollup: ^4.53.3
  scule: ^1.3.0
  sh-syntax: 0.5.8
  shiki: ^4.0.2
  tinyexec: ^1.1.1
  tsx: ^4.21.0
  typescript: ^6.0.2
  ufo: ^1.6.1
  unctx: ^2.4.1
  unimport: ^6.0.2
  unstorage: ^2.0.0-alpha.7
  valibot: ^1.3.1
  vite: ^8.0.8
  vitest: ^4.1.4
  vue-tsc: ^3.2.6
  xdg-portable: ^7.3.0

catalogMode: prefer

catalogs:
  backend:
    better-sqlite3: ^12.6.2
  build:
    typescript: ^6.0.2
  frontend:
    docus: ^5.9.0
    nitro: ^3.0.0
    nuxt: ^4.4.2
  h3v1:
    h3: ^1.15.11
  h3v2:
    h3: ^2.0.1-rc.20
  lint:
    oxlint: ^1.58.0
  script:
    tsx: ^4.20.3
  test:
    vitest: ^4.0.16
  types:
    "@types/node": ^25.6.0
patchedDependencies:
  h3@2.0.1-rc.20: patches/h3@2.0.1-rc.20.patch
