overrides:
  '@vite-hub/ui': https://pkg.pr.new/vite-hub/vitehub/@vite-hub/ui@930ffa25b2c9de77eedc6f88cc192e497fd4a1ff

patchedDependencies:
  '@vite-hub/agent@0.0.1': patches/@vite-hub__agent@0.0.1.patch
