import { mkdir, readFile, rm, writeFile } from "node:fs/promises"
import { join } from "node:path"

import type { Nitro } from "nitro/types"

import { discoverQueueDefinitions } from "../discovery.ts"
import { getVercelQueueTopicName } from "./vercel-topic.ts"
import type { DiscoveredQueueDefinition, QueueModuleOptions } from "../types.ts"
import { normalizeQueueOptions } from "../config.ts"

type VercelQueueTrigger = {
  consumer: string
  topic: string
  type: "queue/v2beta"
}

type VercelFunctionConfig = {
  experimentalTriggers?: VercelQueueTrigger[]
  [key: string]: unknown
}

type QueueBuildOutputNitro = Nitro & {
  __vitehubQueueVercelBuildOutputApplied?: boolean
}

const generatedFunctionPrefix = "functions/api/vitehub/queues/vercel"
const generatedSourceHeader = "// Generated by @vitehub/queue Vercel build output support. Do not edit."

function toGeneratedPathSegments(name: string) {
  const segments = name.split("/").filter(Boolean).map(segment => encodeURIComponent(segment))
  return segments.length > 0 ? segments : ["index"]
}

function createTargetRoute(name: string) {
  return `/_vitehub/queues/vercel/${name}`
}

function createFunctionDir(outputDir: string, name: string) {
  const segments = toGeneratedPathSegments(name)
  const last = `${segments.pop() || "index"}.func`
  return join(outputDir, generatedFunctionPrefix, ...segments, last)
}

function createDelegatingWrapperContents(route: string) {
  // Consumer functions are deployed as isolated bundles on Vercel, so we
  // cannot `import` the main server. Instead, forward the incoming queue
  // request (CloudEvents POST) to the main server over HTTP using the
  // deployment's VERCEL_URL, which Vercel injects at runtime.
  return [
    generatedSourceHeader,
    `const route = ${JSON.stringify(route)}`,
    "",
    "function resolveOrigin() {",
    "  const url = process.env.VERCEL_URL",
    "  if (!url) throw new Error('[vitehub] VERCEL_URL missing; queue consumer needs it to forward to main server.')",
    "  return url.startsWith('http') ? url : `https://${url}`",
    "}",
    "",
    "async function forward(request) {",
    "  const origin = resolveOrigin()",
    "  const target = new URL(route, origin)",
    "  const init = {",
    "    method: request.method,",
    "    headers: request.headers,",
    "    body: request.method === 'GET' || request.method === 'HEAD' ? undefined : await request.arrayBuffer(),",
    "    redirect: 'manual',",
    "  }",
    "  return await fetch(target, init)",
    "}",
    "",
    "export default {",
    "  async fetch(request) {",
    "    return await forward(request)",
    "  },",
    "}",
    "",
  ].join("\n")
}

export function shouldConfigureVercelQueueBuildOutput(
  nitro: Nitro,
  queueConfig: QueueModuleOptions | undefined,
): boolean {
  if (queueConfig === false || nitro.options.dev) return false

  const hosting = nitro.options.preset || process.env.NITRO_PRESET || ""
  if (!hosting.includes("vercel")) return false

  return normalizeQueueOptions(queueConfig, { hosting })?.provider.provider === "vercel"
}

export async function syncVercelQueueBuildOutput(nitro: Nitro, definitions: DiscoveredQueueDefinition[]) {
  if (!definitions.length) return

  const outputDir = nitro.options.output.dir
  const serverDir = nitro.options.output.serverDir
  const generatedFunctionsDir = join(outputDir, generatedFunctionPrefix)
  const serverConfigPath = join(serverDir, ".vc-config.json")
  let baseFunctionConfig: VercelFunctionConfig

  try {
    baseFunctionConfig = JSON.parse(await readFile(serverConfigPath, "utf8")) as VercelFunctionConfig
  }
  catch (error) {
    throw new Error(`[vitehub] Missing Vercel server function config: ${serverConfigPath}`, {
      cause: error instanceof Error ? error : undefined,
    })
  }

  await rm(generatedFunctionsDir, { recursive: true, force: true })

  for (const definition of definitions) {
    const functionDir = createFunctionDir(outputDir, definition.name)
    const route = createTargetRoute(definition.name)
    await mkdir(functionDir, { recursive: true })
    await writeFile(
      join(functionDir, "index.mjs"),
      createDelegatingWrapperContents(route),
      "utf8",
    )
    await writeFile(join(functionDir, ".vc-config.json"), `${JSON.stringify({
      ...baseFunctionConfig,
      experimentalTriggers: [{
        consumer: getVercelQueueTopicName(definition.name),
        topic: getVercelQueueTopicName(definition.name),
        type: "queue/v2beta",
      }],
    }, null, 2)}\n`, "utf8")
  }
}

function shouldApplySupport(nitro: Nitro, queueConfig: QueueModuleOptions | undefined): boolean {
  const target = nitro as QueueBuildOutputNitro
  return !target.__vitehubQueueVercelBuildOutputApplied && shouldConfigureVercelQueueBuildOutput(nitro, queueConfig)
}

export function setupVercelQueueBuildOutputSupport(
  nitro: Nitro,
  queueConfig: QueueModuleOptions | undefined,
  definitions: DiscoveredQueueDefinition[],
): void {
  if (!shouldApplySupport(nitro, queueConfig)) return
  ;(nitro as QueueBuildOutputNitro).__vitehubQueueVercelBuildOutputApplied = true

  const resolvedDefinitions = definitions.length ? definitions : discoverQueueDefinitions(nitro.options)
  if (!resolvedDefinitions.length) return

  nitro.hooks.hook("compiled", async () => {
    await syncVercelQueueBuildOutput(nitro, resolvedDefinitions)
  })
}
