import { mkdir, readFile, rm, writeFile } from "node:fs/promises"
import { join, relative } from "node:path"

import type { Nitro } from "nitro/types"

import { discoverQueueDefinitions } from "../discovery.ts"
import { getVercelQueueTopicName } from "./vercel-topic.ts"
import type { DiscoveredQueueDefinition, QueueModuleOptions } from "../types.ts"
import { normalizeQueueOptions } from "../config.ts"

type VercelQueueTrigger = {
  topic: string
  type: "queue/v2beta"
}

type VercelFunctionConfig = {
  experimentalTriggers?: VercelQueueTrigger[]
  [key: string]: unknown
}

type QueueBuildOutputNitro = Nitro & {
  __vitehubQueueVercelBuildOutputApplied?: boolean
}

const generatedFunctionPrefix = "functions/api/vitehub/queues/vercel"
const generatedSourceHeader = "// Generated by @vitehub/queue Vercel build output support. Do not edit."

function toGeneratedPathSegments(name: string) {
  const segments = name.split("/").filter(Boolean).map(segment => encodeURIComponent(segment))
  return segments.length > 0 ? segments : ["index"]
}

function createTargetRoute(name: string) {
  return `/_vitehub/queues/vercel/${name}`
}

function createFunctionDir(outputDir: string, name: string) {
  const segments = toGeneratedPathSegments(name)
  const last = `${segments.pop() || "index"}.func`
  return join(outputDir, generatedFunctionPrefix, ...segments, last)
}

function toImportPath(path: string) {
  return path.startsWith(".") ? path : `./${path}`
}

function createDelegatingWrapperContents(route: string, serverEntryImport: string) {
  return [
    generatedSourceHeader,
    `import server from ${JSON.stringify(serverEntryImport)}`,
    "",
    `const route = ${JSON.stringify(route)}`,
    "",
    "function rewriteNodeRequestUrl(url) {",
    "  const target = new URL(url || route, 'https://vitehub.local')",
    "  target.pathname = route",
    "  return `${target.pathname}${target.search}`",
    "}",
    "",
    "const handler = typeof server === 'function'",
    "  ? function queueHandler(req, res) {",
    "      req.url = rewriteNodeRequestUrl(req.url)",
    "      return server(req, res)",
    "    }",
    "  : {",
    "      fetch(req, context) {",
    "        const target = new URL(req.url)",
    "        target.pathname = route",
    "        return server.fetch(new Request(target, req), context)",
    "      },",
    "    }",
    "",
    "export default handler",
    "",
  ].join("\n")
}

export function shouldConfigureVercelQueueBuildOutput(
  nitro: Nitro,
  queueConfig: QueueModuleOptions | undefined,
): boolean {
  if (queueConfig === false || nitro.options.dev) return false

  const hosting = process.env.NITRO_PRESET || nitro.options.preset
  if (hosting !== "vercel") return false

  return normalizeQueueOptions(queueConfig, { hosting })?.provider.provider === "vercel"
}

export async function syncVercelQueueBuildOutput(nitro: Nitro, definitions: DiscoveredQueueDefinition[]) {
  if (!definitions.length) return

  const outputDir = nitro.options.output.dir
  const serverDir = nitro.options.output.serverDir
  const serverEntry = join(serverDir, "index.mjs")
  const generatedFunctionsDir = join(outputDir, generatedFunctionPrefix)
  const serverConfigPath = join(serverDir, ".vc-config.json")
  let baseFunctionConfig: VercelFunctionConfig

  try {
    baseFunctionConfig = JSON.parse(await readFile(serverConfigPath, "utf8")) as VercelFunctionConfig
  }
  catch (error) {
    throw new Error(`[vitehub] Missing Vercel server function config: ${serverConfigPath}`, {
      cause: error instanceof Error ? error : undefined,
    })
  }

  await rm(generatedFunctionsDir, { recursive: true, force: true })

  for (const definition of definitions) {
    const functionDir = createFunctionDir(outputDir, definition.name)
    const route = createTargetRoute(definition.name)
    await mkdir(functionDir, { recursive: true })
    await writeFile(
      join(functionDir, "index.mjs"),
      createDelegatingWrapperContents(route, toImportPath(relative(functionDir, serverEntry).replace(/\\/g, "/"))),
      "utf8",
    )
    await writeFile(join(functionDir, ".vc-config.json"), `${JSON.stringify({
      ...baseFunctionConfig,
      experimentalTriggers: [{
        topic: getVercelQueueTopicName(definition.name),
        type: "queue/v2beta",
      }],
    }, null, 2)}\n`, "utf8")
  }
}

export function setupVercelQueueBuildOutputSupport(
  nitro: Nitro,
  queueConfig: QueueModuleOptions | undefined,
  definitions: DiscoveredQueueDefinition[],
): void {
  const target = nitro as QueueBuildOutputNitro
  if (target.__vitehubQueueVercelBuildOutputApplied || !shouldConfigureVercelQueueBuildOutput(nitro, queueConfig)) return

  target.__vitehubQueueVercelBuildOutputApplied = true
  const resolvedDefinitions = definitions.length ? definitions : discoverQueueDefinitions(nitro.options)
  if (!resolvedDefinitions.length) return

  nitro.hooks.hook("compiled", async () => {
    await syncVercelQueueBuildOutput(nitro, resolvedDefinitions)
  })
}
