import { H3, readValidatedBody } from "h3"
import * as v from "valibot"

import { useWorkspace } from "@vitehub/workspace"
import { getWorkspaceRuntimeConfig } from "@vitehub/workspace/runtime/state"

const app = new H3()
const writeBody = v.optional(v.object({
  path: v.optional(v.string()),
  content: v.optional(v.string()),
}), {})

app.get("/", () => ({ ok: true, workspace: "docs" }))

app.get("/api/workspace", async () => {
  const workspace = await useWorkspace("docs")
  await workspace.sync()
  const runtimeConfig = getWorkspaceRuntimeConfig()
  const generatedPath = "generated/notes.md"
  return {
    ok: true,
    provider: runtimeConfig ? runtimeConfig.store.provider : "local",
    files: await workspace.list("", { recursive: true }),
    markdown: await workspace.glob("**/*.md"),
    readme: await workspace.readFile("README.md"),
    generated: await workspace.exists(generatedPath) ? await workspace.readFile(generatedPath) : null,
  }
})

app.post("/api/workspace/write", async (event) => {
  const body = await readValidatedBody(event, writeBody)
  const workspace = await useWorkspace("docs")
  await workspace.sync()
  const snapshot = await workspace.snapshot({ name: "write-baseline" })
  const path = body?.path || "generated/notes.md"
  await workspace.writeFile(path, body?.content || "Generated by Vite playground\n")
  const diff = await workspace.diff({ from: snapshot })
  const committedSnapshot = await workspace.snapshot({ name: "write-commit" })
  const runtimeConfig = getWorkspaceRuntimeConfig()
  return {
    ok: true,
    provider: runtimeConfig ? runtimeConfig.store.provider : "local",
    snapshot,
    committedSnapshot,
    diff,
    readBack: await workspace.readFile(path),
  }
})

export default app
