import { H3, readValidatedBody } from "h3"
import * as v from "valibot"

import { useWorkspace } from "@vitehub/workspace"

const app = new H3()
const writeBody = v.optional(v.object({
  path: v.optional(v.string()),
  content: v.optional(v.string()),
}), {})

app.get("/", () => ({ ok: true, workspace: "docs" }))

app.get("/api/workspace", async () => {
  const workspace = await useWorkspace("docs")
  await workspace.sync()
  return {
    ok: true,
    files: await workspace.list("", { recursive: true }),
    markdown: await workspace.glob("**/*.md"),
    readme: await workspace.readFile("README.md"),
  }
})

app.post("/api/workspace/write", async (event) => {
  const body = await readValidatedBody(event, writeBody)
  const workspace = await useWorkspace("docs")
  await workspace.sync()
  const snapshot = await workspace.snapshot({ name: "write-baseline" })
  await workspace.writeFile(body?.path || "generated/notes.md", body?.content || "Generated by Vite playground\n")
  return {
    ok: true,
    snapshot,
    diff: await workspace.diff({ from: snapshot }),
  }
})

export default app
