import { H3, getQuery, readValidatedBody } from "h3"
import * as v from "valibot"

import { useWorkspace } from "@vitehub/workspace"
import { getWorkspaceRuntimeConfig, resetWorkspaceStoreCache } from "@vitehub/workspace/runtime/state"

const app = new H3()
const writeBody = v.optional(v.object({
  path: v.optional(v.string()),
  content: v.optional(v.string()),
}), {})

app.get("/", () => ({ ok: true, workspace: "docs" }))

app.get("/api/workspace", async () => {
  const workspace = useWorkspace("docs", { allowWrite: true })
  const runtimeConfig = getWorkspaceRuntimeConfig()
  const generatedPath = "generated/notes.md"
  return {
    ok: true,
    provider: runtimeConfig ? runtimeConfig.store.provider : "local",
    files: await workspace.fs.list("", { recursive: true }),
    markdown: await workspace.fs.glob("**/*.md"),
    readme: await workspace.fs.readFile("README.md"),
    generated: await workspace.fs.exists(generatedPath) ? await workspace.fs.readFile(generatedPath) : null,
  }
})

app.post("/api/workspace/write", async (event) => {
  const body = await readValidatedBody(event, writeBody)
  const workspace = useWorkspace("docs", { allowWrite: true })
  const path = body?.path || "generated/notes.md"
  await workspace.fs.writeFile(path, body?.content || "Generated by Vite playground\n")
  const runtimeConfig = getWorkspaceRuntimeConfig()
  return {
    ok: true,
    provider: runtimeConfig ? runtimeConfig.store.provider : "local",
    path,
    readBack: await workspace.fs.readFile(path),
  }
})

app.get("/api/workspace/read-fresh", async (event) => {
  const query = getQuery(event)
  const path = typeof query.path === "string" ? query.path : "generated/notes.md"
  resetWorkspaceStoreCache()
  const workspace = useWorkspace("docs", { allowWrite: true })
  const runtimeConfig = getWorkspaceRuntimeConfig()
  return {
    ok: true,
    provider: runtimeConfig ? runtimeConfig.store.provider : "local",
    path,
    readBack: await workspace.fs.exists(path) ? await workspace.fs.readFile(path) : null,
  }
})

export default app
