import { defineConfig } from "tsdown"

export default defineConfig({
  clean: true,
  dts: true,
  entry: [
    "src/arrays.ts",
    "src/definition-catalog.ts",
    "src/definition-discovery.ts",
    "src/env.ts",
    "src/http-request.ts",
    "src/nitro.ts",
    "src/object.ts",
    "src/source-scanner.ts",
    "src/workspace-inventory.ts",
    "src/build/client-output.ts",
    "src/build/cloudflare.ts",
    "src/build/deployment-output.ts",
    "src/build/esbuild.ts",
    "src/build/mode.ts",
    "src/build/paths.ts",
    "src/build/user-entry.ts",
    "src/build/vercel-config.ts",
    "src/build/vite.ts",
    "src/feature-bridge/feature-engine.ts",
    "src/feature-bridge/hosting.ts",
    "src/integrations/hex.ts",
    "src/runtime/app.ts",
    "src/runtime/cloudflare-env.ts",
    "src/runtime/cloudflare-hosted.ts",
    "src/runtime/context.ts",
    "src/runtime/hosted.ts",
    "src/runtime/random.ts",
    "src/runtime/vercel-hosted.ts",
  ],
  format: ["esm"],
  outExtensions: () => ({
    dts: ".d.ts",
    js: ".js",
  }),
  publint: false,
})
