import { defineConfig } from "vite-plus";

export default defineConfig({
  pack: {
    dts: true,
    entry: [
      "src/agent-workflow.ts",
      "src/arrays.ts",
      "src/cli.ts",
      "src/definition-catalog.ts",
      "src/definition-discovery.ts",
      "src/deployment.ts",
      "src/env.ts",
      "src/effect.ts",
      "src/http-request.ts",
      "src/object.ts",
      "src/provision.ts",
      "src/provision-state.ts",
      "src/source-scanner.ts",
      "src/workspace-inventory.ts",
      "src/build/client-output.ts",
      "src/build/cloudflare.ts",
      "src/build/colocated-agent-files.ts",
      "src/build/deployment-output.ts",
      "src/build/deployment-plan-output.ts",
      "src/build/deno-runtime-packages.ts",
      "src/build/esbuild.ts",
      "src/build/mode.ts",
      "src/build/paths.ts",
      "src/build/user-entry.ts",
      "src/build/vercel-config.ts",
      "src/build/vercel-runtime-package-copy.ts",
      "src/build/vercel-runtime-packages.ts",
      "src/build/vite.ts",
      "src/hosting.ts",
      "src/integrations/hex.ts",
      "src/runtime/app.ts",
      "src/runtime/cloudflare-env.ts",
      "src/runtime/cloudflare-hosted.ts",
      "src/runtime/hosted.ts",
      "src/runtime/random.ts",
      "src/runtime/time-zone.ts",
      "src/runtime/vercel-hosted.ts",
    ],
    outExtensions: () => ({
      dts: ".d.ts",
      js: ".js",
    }),
    publint: false,
  },
});
