import { defineConfig } from "vite-plus"

export default defineConfig({
  pack: {
    tsconfig: "tsconfig.build.json",
    deps: {
      neverBundle: [
        "vite",
        /^@vite-hub\/(?:agent|blob|database|devtools|env|kv|queue|sandbox|schedule|workflow|workspace)(?:\/.*)?$/,
      ],
      onlyBundle: false,
    },
    entry: [
      "src/agent.ts",
      "src/agent/capabilities.ts",
      "src/agent/channels.ts",
      "src/agent/cloudflare.ts",
      "src/agent/cloudflare/state.ts",
      "src/agent/eval.ts",
      "src/agent/harness/local-sandbox.ts",
      "src/agent/mcp.ts",
      "src/agent/mcp/stdio.ts",
      "src/agent/runtime/workflow.ts",
      "src/agent/server.ts",
      "src/agent/server/workspace.ts",
      "src/agent/state/sqlite.ts",
      "src/blob.ts",
      "src/blob/drivers/akamai.ts",
      "src/blob/drivers/azure.ts",
      "src/blob/drivers/box.ts",
      "src/blob/drivers/cloudflare.ts",
      "src/blob/drivers/digitalocean-spaces.ts",
      "src/blob/drivers/dropbox.ts",
      "src/blob/drivers/files.ts",
      "src/blob/drivers/files-sdk.ts",
      "src/blob/drivers/fs.ts",
      "src/blob/drivers/gcs.ts",
      "src/blob/drivers/google-drive.ts",
      "src/blob/drivers/hetzner.ts",
      "src/blob/drivers/minio.ts",
      "src/blob/drivers/netlify-blobs.ts",
      "src/blob/drivers/onedrive.ts",
      "src/blob/drivers/s3.ts",
      "src/blob/drivers/storj.ts",
      "src/blob/drivers/supabase.ts",
      "src/blob/drivers/uploadthing.ts",
      "src/blob/drivers/vercel.ts",
      "src/blob/drivers/vercel-bundled.ts",
      "src/blob/ensure.ts",
      "src/blob/storage.ts",
      "src/database.ts",
      "src/database/drizzle.ts",
      "src/env.ts",
      "src/env/secret.ts",
      "src/env/server.ts",
      "src/env/vite.ts",
      "src/index.ts",
      "src/kv.ts",
      "src/queue.ts",
      "src/sandbox.ts",
      "src/sandbox/runtime/provider-loader.ts",
      "src/sandbox/runtime/state.ts",
      "src/schedule.ts",
      "src/schedule/runtime.ts",
      "src/schedule/runtime/state.ts",
      "src/schedule/runtime/static.ts",
      "src/workflow.ts",
      "src/workflow/runtime/execute.ts",
      "src/workflow/runtime/state.ts",
      "src/workspace.ts",
      "src/workspace/cloudflare.ts",
      "src/workspace/loader.ts",
      "src/workspace/publish.ts",
      "src/workspace/runtime.ts",
      "src/workspace/server.ts",
    ],
    exports: {
      inlinedDependencies: false,
    },
    outExtensions: () => ({
      dts: ".d.ts",
      js: ".js",
    }),
    publint: true,
  },
})
