import { readdir, readFile } from "node:fs/promises"
import { join, resolve } from "node:path"

import { expect, it } from "vitest"

const consoleRoot = resolve(import.meta.dirname, "../src/console")
const iconPattern = /\bi-(lucide|ph)-([a-z0-9]+(?:-[a-z0-9]+)*)/g

async function sourceIcons(root: string): Promise<string[]> {
  const icons = new Set<string>()
  for (const entry of await readdir(root, { recursive: true, withFileTypes: true })) {
    if (!entry.isFile() || !/\.(?:ts|vue)$/.test(entry.name)) continue
    const source = await readFile(join(entry.parentPath, entry.name), "utf8")
    for (const [, collection, name] of source.matchAll(iconPattern)) icons.add(`${collection}:${name}`)
  }
  return [...icons].sort()
}

it("lists every icon that the Console sources use", async () => {
  const icons = await sourceIcons(consoleRoot)
  expect(icons.length).toBeGreaterThan(0)
  await expect([
    "// Generated by test/console-icons.test.ts from the Console sources.",
    "// Run `vp test test/console-icons.test.ts -u` in packages/vite-hub after you add or remove a Console icon.",
    "export const consoleIcons: readonly string[] = [",
    ...icons.map(icon => `  "${icon}",`),
    "]",
    "",
  ].join("\n")).toMatchFileSnapshot("../src/console/icons.ts")
})
