export const EXEC_STDIO_OUTPUT_MARKER = '__VITEHUB_OUTPUT__'

export function createEntrySource(definitionPath: string, execution: 'definition' | 'module' = 'definition') {
  const invocation = execution === 'module'
    ? [
        `    const mod = await import(pathToFileURL(${JSON.stringify(definitionPath)}).href)`,
        `    const exported = await mod.default`,
        `    const result = typeof exported === 'function' ? await exported(input.payload, input.context) : exported`,
        `    if (result && typeof result === 'object' && typeof result.run === 'function')`,
        `      throw new TypeError('Sandbox package entrypoints execute at module top level; remove defineSandbox({ run }).')`,
        `    if (typeof result === 'undefined')`,
        `      throw new TypeError('Sandbox package entrypoint must default-export a result.')`,
      ]
    : [
        `    const mod = await import(pathToFileURL(${JSON.stringify(definitionPath)}).href)`,
        `    const definition = mod?.default`,
        `    if (!definition || typeof definition.run !== 'function')`,
        `      throw new Error('Sandbox Definition must default-export defineSandbox({ run }).')`,
        `    const result = await definition.run(input.payload, input.context)`,
      ]
  return [
    `import { mkdir, readFile, writeFile } from 'node:fs/promises'`,
    `import { pathToFileURL } from 'node:url'`,
    ``,
    `function normalizeError(error) {`,
    `  if (error instanceof Error) {`,
    `    return {`,
    `      name: error.name,`,
    `      message: error.message,`,
    `      stack: error.stack,`,
    `      cause: error.cause ? String(error.cause) : undefined,`,
    `    }`,
    `  }`,
    `  return {`,
    `    name: 'Error',`,
    `    message: String(error),`,
    `  }`,
    `}`,
    ``,
    `const valueMarker = ${JSON.stringify('__vitehubSandboxValue')}`,
    ``,
    `function isPlainObject(value) {`,
    `  if (!value || typeof value !== 'object') return false`,
    `  const prototype = Object.getPrototypeOf(value)`,
    `  return prototype === Object.prototype || prototype === null`,
    `}`,
    ``,
    `function hasMarker(value) {`,
    `  return Object.prototype.hasOwnProperty.call(value, valueMarker)`,
    `}`,
    ``,
    `function invalidDescriptor(label) {`,
    `  return new TypeError('Sandbox ' + label + ' contains an invalid binary sidecar descriptor.')`,
    `}`,
    ``,
    `async function reviveValue(value, assetsDir, label) {`,
    `  if (Array.isArray(value))`,
    `    return await Promise.all(value.map(entry => reviveValue(entry, assetsDir, label)))`,
    `  if (!isPlainObject(value)) return value`,
    `  if (!hasMarker(value)) {`,
    `    return Object.fromEntries(await Promise.all(Object.entries(value).map(async ([key, entry]) => [`,
    `      key,`,
    `      await reviveValue(entry, assetsDir, label),`,
    `    ])))`,
    `  }`,
    `  const descriptor = value[valueMarker]`,
    `  if (!isPlainObject(descriptor) || typeof descriptor.tag !== 'string')`,
    `    throw invalidDescriptor(label)`,
    `  if (descriptor.tag === 'object') {`,
    `    if (!Array.isArray(descriptor.entries) || !descriptor.entries.every(entry => Array.isArray(entry) && entry.length === 2 && typeof entry[0] === 'string'))`,
    `      throw invalidDescriptor(label)`,
    `    return Object.fromEntries(await Promise.all(descriptor.entries.map(async ([key, entry]) => [`,
    `      key,`,
    `      await reviveValue(entry, assetsDir, label),`,
    `    ])))`,
    `  }`,
    `  if (descriptor.tag !== 'binary'`,
    `    || !Number.isSafeInteger(descriptor.id)`,
    `    || Object.is(descriptor.id, -0)`,
    `    || descriptor.id < 0`,
    `    || (descriptor.kind !== 'blob' && descriptor.kind !== 'uint8array')`,
    `    || (typeof descriptor.type !== 'undefined' && typeof descriptor.type !== 'string'))`,
    `    throw invalidDescriptor(label)`,
    `  const bytes = new Uint8Array(await readFile(assetsDir + '/' + descriptor.id))`,
    `  return descriptor.kind === 'blob' ? new Blob([bytes], { type: descriptor.type || '' }) : bytes`,
    `}`,
    ``,
    `async function extractValue(value, assetsDir, state = { nextId: 0 }, ancestors = new Set()) {`,
    `  const blob = typeof Blob !== 'undefined' && value instanceof Blob`,
    `  if (blob || value instanceof Uint8Array) {`,
    `    const id = state.nextId++`,
    `    state.directory ||= mkdir(assetsDir, { recursive: true })`,
    `    await state.directory`,
    `    const bytes = blob ? new Uint8Array(await value.arrayBuffer()) : value`,
    `    await writeFile(assetsDir + '/' + id, bytes)`,
    `    return { [valueMarker]: {`,
    `      id,`,
    `      kind: blob ? 'blob' : 'uint8array',`,
    `      ...(blob && value.type ? { type: value.type } : {}),`,
    `      tag: 'binary',`,
    `    } }`,
    `  }`,
    `  if (Array.isArray(value)) {`,
    `    if (ancestors.has(value))`,
    `      throw new TypeError('Sandbox result must be JSON-serializable; cyclic value.')`,
    `    const nextAncestors = new Set(ancestors).add(value)`,
    `    return await Promise.all(value.map(entry => extractValue(entry, assetsDir, state, nextAncestors)))`,
    `  }`,
    `  if (!isPlainObject(value)) return value`,
    `  if (ancestors.has(value))`,
    `    throw new TypeError('Sandbox result must be JSON-serializable; cyclic value.')`,
    `  const nextAncestors = new Set(ancestors).add(value)`,
    `  const entries = await Promise.all(Object.entries(value).map(async ([key, entry]) => [`,
    `    key,`,
    `    await extractValue(entry, assetsDir, state, nextAncestors),`,
    `  ]))`,
    `  return hasMarker(value) ? { [valueMarker]: { entries, tag: 'object' } } : Object.fromEntries(entries)`,
    `}`,
    ``,
    `async function serializeSuccess(result, assetsDir) {`,
    `  const encoded = await extractValue(result, assetsDir)`,
    `  try {`,
    `    return JSON.stringify({ ok: true, result: encoded }, (key, value) => {`,
    `      const type = typeof value`,
    `      if (type === 'undefined' || type === 'function' || type === 'symbol' || type === 'bigint')`,
    `        throw new TypeError('Sandbox result must be JSON-serializable; unsupported ' + type + (key ? ' at "' + key + '".' : '.'))`,
    `      if (type === 'number' && !Number.isFinite(value))`,
    `        throw new TypeError('Sandbox result must be JSON-serializable; non-finite number' + (key ? ' at "' + key + '".' : '.'))`,
    `      return value`,
    `    })`,
    `  }`,
    `  catch (error) {`,
    `    if (error instanceof TypeError && error.message.startsWith('Sandbox result must be JSON-serializable'))`,
    `      throw error`,
    `    throw new TypeError('Sandbox result must be JSON-serializable.', { cause: error })`,
    `  }`,
    `}`,
    ``,
    `export async function main(argv = process.argv.slice(2)) {`,
    `  const [inputPath, outputPath] = argv`,
    `  try {`,
    `    const raw = await readFile(inputPath, 'utf8')`,
    `    const input = await reviveValue(JSON.parse(raw || '{}'), inputPath + '.files', 'input')`,
    ...invocation,
    `    const output = await serializeSuccess(result, outputPath + '.files')`,
    `    await writeFile(outputPath, output)`,
    `    console.log('${EXEC_STDIO_OUTPUT_MARKER}' + output)`,
    `  }`,
    `  catch (error) {`,
    `    const output = JSON.stringify({ ok: false, error: normalizeError(error) })`,
    `    await writeFile(outputPath, output)`,
    `    console.error('${EXEC_STDIO_OUTPUT_MARKER}' + output)`,
    `    process.exitCode = 1`,
    `  }`,
    `}`,
    ``,
    `await main()`,
    ``,
  ].join('\n')
}
