export const EXEC_STDIO_OUTPUT_MARKER = '__VITEHUB_OUTPUT__'

export function createEntrySource(definitionPath: string, execution: 'definition' | 'module' = 'definition') {
  const invocation = execution === 'module'
    ? [
        `    const mod = await import(pathToFileURL(${JSON.stringify(definitionPath)}).href)`,
        `    const result = await mod.default`,
        `    if (result && typeof result === 'object' && typeof result.run === 'function')`,
        `      throw new TypeError('Sandbox package entrypoints execute at module top level; remove defineSandbox({ run }).')`,
        `    if (typeof result === 'function')`,
        `      throw new TypeError('Sandbox package entrypoint must default-export its result, not a function.')`,
        `    if (typeof result === 'undefined')`,
        `      throw new TypeError('Sandbox package entrypoint must default-export a result.')`,
      ]
    : [
        `    const raw = await readFile(inputPath, 'utf8')`,
        `    const input = JSON.parse(raw || '{}')`,
        `    const mod = await import(pathToFileURL(${JSON.stringify(definitionPath)}).href)`,
        `    const definition = mod?.default`,
        `    if (!definition || typeof definition.run !== 'function')`,
        `      throw new Error('Sandbox Definition must default-export defineSandbox({ run }).')`,
        `    const result = await definition.run(input.payload, input.context)`,
      ]
  return [
    `import { readFile, writeFile } from 'node:fs/promises'`,
    `import { pathToFileURL } from 'node:url'`,
    ``,
    `function normalizeError(error) {`,
    `  if (error instanceof Error) {`,
    `    return {`,
    `      name: error.name,`,
    `      message: error.message,`,
    `      stack: error.stack,`,
    `      cause: error.cause ? String(error.cause) : undefined,`,
    `    }`,
    `  }`,
    `  return {`,
    `    name: 'Error',`,
    `    message: String(error),`,
    `  }`,
    `}`,
    ``,
    `function serializeSuccess(result) {`,
    `  try {`,
    `    return JSON.stringify({ ok: true, result }, (key, value) => {`,
    `      const type = typeof value`,
    `      if (type === 'undefined' || type === 'function' || type === 'symbol' || type === 'bigint')`,
    `        throw new TypeError('Sandbox result must be JSON-serializable; unsupported ' + type + (key ? ' at "' + key + '".' : '.'))`,
    `      if (type === 'number' && !Number.isFinite(value))`,
    `        throw new TypeError('Sandbox result must be JSON-serializable; non-finite number' + (key ? ' at "' + key + '".' : '.'))`,
    `      return value`,
    `    })`,
    `  }`,
    `  catch (error) {`,
    `    if (error instanceof TypeError && error.message.startsWith('Sandbox result must be JSON-serializable'))`,
    `      throw error`,
    `    throw new TypeError('Sandbox result must be JSON-serializable.', { cause: error })`,
    `  }`,
    `}`,
    ``,
    `export async function main(argv = process.argv.slice(2)) {`,
    `  const [inputPath, outputPath] = argv`,
    `  try {`,
    ...invocation,
    `    const output = serializeSuccess(result)`,
    `    await writeFile(outputPath, output)`,
    `    console.log('${EXEC_STDIO_OUTPUT_MARKER}' + output)`,
    `  }`,
    `  catch (error) {`,
    `    const output = JSON.stringify({ ok: false, error: normalizeError(error) })`,
    `    await writeFile(outputPath, output)`,
    `    console.error('${EXEC_STDIO_OUTPUT_MARKER}' + output)`,
    `    process.exitCode = 1`,
    `  }`,
    `}`,
    ``,
    `await main()`,
    ``,
  ].join('\n')
}
