import { H3 } from "h3"
import { useWorkspace } from "@vite-hub/workspace"

const app = new H3()

app.get("/api/workspace", async () => {
  const workspace = useWorkspace("docs", { mode: "write" })
  await workspace.fs.writeFile("generated/notes.md", "Generated by Vite\n")

  return {
    ok: true,
    files: await workspace.fs.glob("**/*.md"),
  }
})

export default app
