import { H3 } from "h3"
import { useWorkspace } from "@vitehub/workspace"

const app = new H3()

app.get("/api/workspace", async () => {
  const workspace = await useWorkspace("docs")
  await workspace.sync()
  await workspace.writeFile("generated/notes.md", "Generated by Vite\n")

  return {
    ok: true,
    files: await workspace.glob("**/*.md"),
    diff: await workspace.diff(),
  }
})

export default app
