import { mkdtemp, readFile, rm } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { expect, it } from 'vitest'
import { agentHostRoutes } from '../src/host-routes-vite.ts'
import { hasRuntimeType } from '../src/internal/runtime-type.ts'

async function configure(options: Parameters<typeof agentHostRoutes>[0], config: import('vite').UserConfig) {
  const hook = agentHostRoutes(options).config
  if (!hasRuntimeType(hook, 'function')) throw new Error('Expected a config hook')
  // SAFETY: This plugin only reads the supplied configuration, not the Vite hook context.
  return await hook.call({} as never, config, { command: 'build', mode: 'production' })
}

it('generates read-only health and workspace handlers from named module exports', async () => {
  const root = await mkdtemp(join(tmpdir(), 'agent-host-routes-'))
  try {
    const result = await configure({ entry: 'agent.ts', health: 'health', workspace: 'workspace' }, { root })
    expect(result).toMatchObject({ nitro: { handlers: [
      { route: '/api/health', method: 'get' },
      { route: '/api/health', method: 'head' },
      { route: '/api/_vitehub/console/invocations/:id/workspace', method: 'get' },
      { route: '/api/_vitehub/console/invocations/:id/workspace', method: 'head' },
    ] } })
    // SAFETY: The plugin's public result is Nitro configuration generated by the function above.
    const handlers = (result as { nitro: { handlers: { handler: string }[] } }).nitro.handlers
    const health = await readFile(handlers[0]!.handler, 'utf8')
    const workspace = await readFile(handlers[2]!.handler, 'utf8')
    expect(health).toContain('import { health as inspect }')
    expect(health).toContain('inspect()')
    expect(workspace).toContain('import { workspace as inspect }')
    expect(workspace).toContain("getRouterParam(event, 'id')")
    expect(workspace).toContain("typeof path === 'string' ? path : undefined")
    expect(await configure({ entry: 'other.ts', health: { exportName: 'default', route: '/status' } }, { root })).not.toEqual(result)
  } finally { await rm(root, { recursive: true, force: true }) }
})

it.each([
  { health: { exportName: 'health', route: 'relative' } },
  { health: { exportName: 'health', route: '/health?x' } },
  { health: 'bad;name' },
  { workspace: { exportName: 'workspace', route: '/workspace' } },
  { health: { exportName: 'health', route: '/:id' }, workspace: { exportName: 'workspace', route: '/:id' } },
])('rejects malformed or colliding route configuration', async configured => {
  await expect(configure({ entry: 'agent.ts', ...configured }, {})).rejects.toThrow()
})
