import { mkdir, mkdtemp, readFile, rm, symlink, writeFile } from 'node:fs/promises'
import { pathToFileURL } from 'node:url'
import { execFile as execFileCallback } from 'node:child_process'
import { promisify } from 'node:util'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { expect, it } from 'vitest'
import { agentHostRoutes } from '../src/host-routes-vite.ts'
import { hasRuntimeType } from '../src/internal/runtime-type.ts'

async function configure(options: Parameters<typeof agentHostRoutes>[0], config: import('vite').UserConfig) {
  const hook = agentHostRoutes(options).config
  if (!hasRuntimeType(hook, 'function')) throw new Error('Expected a config hook')
  // SAFETY: This plugin only reads the supplied configuration, not the Vite hook context.
  return await hook.call({} as never, config, { command: 'build', mode: 'production' })
}

it('generates read-only health and workspace handlers from named module exports', async () => {
  const root = await mkdtemp(join(tmpdir(), 'agent-host-routes-'))
  try {
    const result = await configure({ entry: 'agent.ts', health: 'health', workspace: 'workspace' }, { root })
    expect(result).toMatchObject({ nitro: { handlers: [
      { route: '/api/health', method: 'get' },
      { route: '/api/health', method: 'head' },
      { route: '/api/_vitehub/console/invocations/:id/workspace', method: 'get' },
      { route: '/api/_vitehub/console/invocations/:id/workspace', method: 'head' },
    ] } })
    // SAFETY: The plugin's public result is Nitro configuration generated by the function above.
    const handlers = (result as { nitro: { handlers: { handler: string }[] } }).nitro.handlers
    const health = await readFile(handlers[0]!.handler, 'utf8')
    const workspace = await readFile(handlers[2]!.handler, 'utf8')
    expect(health).toContain('import { health as inspect }')
    expect(health).toContain('inspect()')
    expect(workspace).toContain('import { workspace as inspect }')
    expect(workspace).toContain("getRouterParam(event, 'id')")
    expect(workspace).toContain("typeof path === 'string' ? path : undefined")
    expect(await configure({ entry: 'other.ts', health: { exportName: 'default', route: '/status' } }, { root })).not.toEqual(result)
  } finally { await rm(root, { recursive: true, force: true }) }
})

it.each([
  { health: { exportName: 'health', route: 'relative' } },
  { health: { exportName: 'health', route: '/health?x' } },
  { health: 'bad;name' },
  { workspace: { exportName: 'workspace', route: '/workspace' } },
  { health: { exportName: 'health', route: '/:id' }, workspace: { exportName: 'workspace', route: '/:id' } },
])('rejects malformed or colliding route configuration', async configured => {
  await expect(configure({ entry: 'agent.ts', ...configured }, {})).rejects.toThrow()
})

it('registers the configured Workspace inspector at host startup without replacing other routes', async () => {
  const root = await mkdtemp(join(tmpdir(), 'agent-host-inspector-'))
  const route = `/host-${crypto.randomUUID()}/:id/workspace`
  try {
    await mkdir(join(root, 'node_modules/@vite-hub'), { recursive: true })
    await symlink(process.cwd(), join(root, 'node_modules/@vite-hub/agent'), 'dir')
    await writeFile(join(root, 'agent.ts'), 'export const workspace = (id, path) => Response.json({ id, path })')
    const result = await configure({ entry: 'agent.ts', workspace: { exportName: 'workspace', route } }, { root })
    // SAFETY: This config hook contributes the Nitro startup plugins asserted by this integration test.
    const plugins = (result as { nitro: { plugins: string[] } }).nitro.plugins
    expect(plugins).toHaveLength(1)
    const { stdout } = await promisify(execFileCallback)(process.execPath, ['--input-type=module', '--eval', `
      import plugin from ${JSON.stringify(pathToFileURL(plugins[0]!).href)}
      import { getAgentHostWorkspaceInspector, agentHostWorkspaceRoute } from '@vite-hub/agent/server'
      plugin()
      const response = await getAgentHostWorkspaceInspector(${JSON.stringify(route)})('retained-run', 'src/index.ts')
      console.log(JSON.stringify({ result: await response.json(), defaultRegistered: Boolean(getAgentHostWorkspaceInspector(agentHostWorkspaceRoute)) }))
    `], { cwd: root, timeout: 10_000 })
    expect(JSON.parse(stdout)).toEqual({ result: { id: 'retained-run', path: 'src/index.ts' }, defaultRegistered: false })
  } finally { await rm(root, { recursive: true, force: true }) }
}, 15_000)
