import { defineConfig } from "tsdown"

export default defineConfig({
  clean: true,
  deps: {
    alwaysBundle: [/^@vitehub\/(devtools|internal)/],
    neverBundle: ["#vitehub/agent/registry", "#vitehub/agent/chat/registry"],
    onlyBundle: false,
  },
  dts: true,
  entry: [
    "src/ai-sdk.ts",
    "src/capabilities.ts",
    "src/capability-runtime.ts",
    "src/chat/index.ts",
    "src/chat/cloudflare.ts",
    "src/chat/devtools.ts",
    "src/chat/nitro.ts",
    "src/chat/runtime/agent-chat.ts",
    "src/chat/runtime/chat-devtools-handler.ts",
    "src/chat/runtime/cloudflare-workers-dev.ts",
    "src/chat/runtime/memory-state.ts",
    "src/chat/runtime/nitro-dev-initialize.ts",
    "src/chat/runtime/nitro-runtime-config.ts",
    "src/chat/runtime/nitro-plugin.ts",
    "src/chat/vercel.ts",
    "src/chat/vite.ts",
    "src/index.ts",
    "src/memory.ts",
    "src/messages.ts",
    "src/cloudflare.ts",
    "src/nitro.ts",
    "src/runtime/empty-registry.ts",
    "src/runtime/nitro-runtime-config.ts",
    "src/tanstack-ai.ts",
    "src/test.ts",
    "src/vercel.ts",
    "src/vite.ts",
  ],
  exports: {
    inlinedDependencies: false,
  },
  format: ["esm"],
  outExtensions: () => ({
    dts: ".d.ts",
    js: ".js",
  }),
  publint: true,
})
