import { defineEventHandler, readBody } from "h3"
import { useWorkspace } from "@vitehub/workspace"
import { ensureDocsWorkspace } from "../../utils/workspace"

export default defineEventHandler(async (event) => {
  const body = await readBody<{ path?: string, content?: string }>(event).catch(() => ({}))
  ensureDocsWorkspace()
  const workspace = await useWorkspace("docs")
  await workspace.sync()
  const snapshot = await workspace.snapshot({ name: "write-baseline" })
  await workspace.writeFile(body.path || "generated/notes.md", body.content || "Generated by Nitro playground\n")
  return {
    ok: true,
    snapshot,
    diff: await workspace.diff({ from: snapshot }),
  }
})
