import { defineEventHandler, readBody } from "h3"
import { useWorkspace } from "@vite-hub/workspace"
import { getWorkspaceRuntimeConfig } from "@vite-hub/workspace/internal/runtime/state"
import { ensureDocsWorkspace } from "../../utils/workspace"

export default defineEventHandler(async (event) => {
  const body = await readBody<{ path?: string, content?: string }>(event).catch(() => ({}))
  ensureDocsWorkspace()
  const workspace = useWorkspace("docs", { mode: "write" })
  const path = body.path || "generated/notes.md"
  await workspace.fs.writeFile(path, body.content || "Generated by Nitro playground\n")
  const runtimeConfig = getWorkspaceRuntimeConfig()
  return {
    ok: true,
    provider: runtimeConfig ? runtimeConfig.store.provider : "local",
    path,
    readBack: await workspace.fs.readFile(path),
  }
})
