import { useWorkspace } from "@vitehub/workspace"

export default defineEventHandler(async () => {
  const workspace = useWorkspace("docs", { allowWrite: true })
  await workspace.fs.writeFile("generated/notes.md", "Generated by Nitro\n")

  return {
    ok: true,
    files: await workspace.fs.glob("**/*.md"),
  }
})
