import { useWorkspace } from "@vite-hub/workspace"

export default defineEventHandler(async () => {
  const workspace = useWorkspace("docs", { mode: "write" })
  await workspace.fs.writeFile("generated/notes.md", "Generated by Nitro\n")

  return {
    ok: true,
    files: await workspace.fs.glob("**/*.md"),
  }
})
