import { useWorkspace } from "@vitehub/workspace"

export default defineEventHandler(async () => {
  const workspace = await useWorkspace("docs")
  await workspace.sync()
  await workspace.writeFile("generated/notes.md", "Generated by Nitro\n")

  return {
    ok: true,
    files: await workspace.glob("**/*.md"),
    diff: await workspace.diff(),
  }
})
