// Generated by test/icons.test.ts from the UI sources.
// Run `vp test test/icons.test.ts -u` in packages/ui after you add or remove a UI icon.
export const viteHubUIIcons: readonly string[] = [
  "lucide:chevron-down",
  "lucide:circle-alert",
  "lucide:database",
  "ph:arrow-square-out-light",
  "ph:paperclip-light",
  "ph:x-light",
];
