import { randomBytes, timingSafeEqual } from "node:crypto"
import { once } from "node:events"
import { chmod, writeFile } from "node:fs/promises"
import { createServer } from "node:net"
import { join } from "node:path"
import type { Server, Socket } from "node:net"
import type { BoxDefinition, BoxFile, BoxPlan, BoxProcess, BoxRuntimeDefinition, BoxSession } from "@vite-hub/box"

import type { AgentInvocationContextStore } from "../types.ts"

import { agentDiagnostics } from "../agent-diagnostics.ts"
import { hasRuntimeType, isRuntimeRecord } from "./runtime-type.ts"

const activeBoxes = new WeakMap<AgentInvocationContextStore, ProviderBoxSession>()

export function activeProviderBox(context: AgentInvocationContextStore) {
  return activeBoxes.get(context)
}

export function setActiveProviderBox(context: AgentInvocationContextStore, session: ProviderBoxSession) {
  activeBoxes.set(context, session)
  return () => {
    if (activeBoxes.get(context) === session) activeBoxes.delete(context)
  }
}

/** Environment names that a Box runtime owns. The relay never forwards them. */
const boxRuntimeEnvironmentKeys = new Set([
  "CODEX_HOME",
  "HOME",
  "INIT_CWD",
  "OLDPWD",
  "PWD",
  "XDG_CACHE_HOME",
  "XDG_CONFIG_HOME",
  "XDG_STATE_HOME",
])
const environmentNamePattern = /^[A-Za-z_][A-Za-z0-9_]*$/
const stderrTailBytes = 64 * 1024
const frameStdout = 1
const frameStderr = 2
const frameExit = 3
const relayCleanupTimeoutMs = 1000

export interface ProviderBoxSession {
  /** The session writes directly to the host checkout without a remote copy. */
  readonly localWorkspace?: boolean
  /** Home files and persisted state can contain credentials unknown to the relay. */
  readonly omitDiagnosticOutput?: boolean
  /** Actual Box environment values, retained only for diagnostic redaction. */
  readonly environment?: Readonly<Record<string, string | undefined>>
  /** Absolute Home path inside the Box. */
  readonly home: string
  /** Resolved Box workspace; a missing path means the Box owns its checkout. */
  readonly workspace?: BoxPlan["workspace"]
  readonly session: BoxSession
  readonly spawn: NonNullable<BoxSession["spawn"]>
}

/** True when the Box runtime can reach loopback services of the ViteHub process. */
export function boxSharesHostNetwork(runtime: BoxRuntimeDefinition): boolean {
  if (runtime === "trusted-host") return true
  if (!isRuntimeRecord(runtime) || !("kind" in runtime)) return false
  if (runtime.kind === "trusted-host") return true
  return runtime.kind === "crabbox" && runtime.network === "direct"
}

/**
 * Resolve and open the Agent Box for one provider invocation.
 * Generated provider files are added to Box Home and cannot replace declared Home files.
 */
export async function openProviderBox<Context>(options: {
  command: string
  context: Context
  definition: BoxDefinition<Context>
  files: Readonly<Record<string, string | Uint8Array>>
  signal?: AbortSignal
}): Promise<ProviderBoxSession> {
  // SAFETY: The split specifier keeps @vite-hub/box optional for bundlers. It resolves to the @vite-hub/box module.
  const { resolveBox } = await import("@vite-hub/" + "box") as typeof import("@vite-hub/box")
  const declared = options.definition.home?.files || {}
  const generated: Record<string, BoxFile<Context>> = {}
  for (const [path, contents] of Object.entries(options.files)) {
    if (Object.hasOwn(declared, path)) {
      throw agentDiagnostics.AGENT_R0950({ message: `[vitehub] Agent Box Home file ${path} is generated by the provider Driver. Remove it from box.home.files.` })
    }
    generated[path] = { contents }
  }
  const environment: Record<string, string> = {}
  const env = Object.fromEntries(Object.entries(options.definition.env ?? {}).map(([name, value]) => [name, async (context: Context) => {
    const resolved = hasRuntimeType(value, "function") ? await value(context) : value
    if (hasRuntimeType(resolved, "string")) environment[name] = resolved
    return resolved
  }]))
  const box = await resolveBox({
    ...options.definition,
    env,
    home: { ...options.definition.home, files: { ...declared, ...generated } },
  }, options.context, { requires: [options.command] })
  const session = await box.open({ signal: options.signal })
  try {
    const spawn = session.spawn
    if (!spawn) {
      throw agentDiagnostics.AGENT_R0951({ message: `[vitehub] Agent Box runtime ${box.plan.runtime} cannot start long-running processes. Use a Box runtime with process support, such as trusted-host or crabbox.` })
    }
    const home = await session.exec("sh", ["-c", "printf %s \"$HOME\""], { signal: options.signal })
    if (!home.ok || !home.stdout.startsWith("/")) {
      throw agentDiagnostics.AGENT_R0952({ message: "[vitehub] Agent Box did not report an absolute HOME path." })
    }
    const omitDiagnosticOutput = Object.keys(declared).length > 0 || Object.keys(options.definition.home?.state ?? {}).length > 0
    return { localWorkspace: box.plan.runtime === "trusted-host", environment, omitDiagnosticOutput, home: home.stdout, session, spawn: spawn.bind(session), workspace: box.plan.workspace }
  }
  catch (error) {
    await session.close().catch(() => undefined)
    throw error
  }
}

export interface ProviderBoxRelayOptions {
  box: ProviderBoxSession
  /** Command that starts the provider inside the Box. */
  command: string
  /** File that receives launch diagnostics in the provider launch diagnostic format. */
  diagnosticPath: string
  /** Select the environment forwarded to the Box process from the provider runtime environment. */
  environment: (environment: Readonly<Record<string, string>>) => Record<string, string>
  /** Private directory for the relay socket and launcher. */
  launchRoot: string
  /** Local provider working directory. Paths below it are mapped to the Box working directory. */
  localRoot: string
  /** Local provider cwd, mapped into the Box before the provider is spawned. */
  localCwd?: string
  /** Remove provider arguments that name local paths the Box cannot read. */
  filterArgs?: (args: readonly string[], mapPath: (value: string) => string | undefined) => string[]
}

export interface ProviderBoxRelay {
  /** Executable that the provider runtime starts instead of the provider binary. */
  readonly launcher: string
  close(): Promise<void>
}

/**
 * Start a local relay. The provider runtime starts the relay launcher as its provider binary.
 * The relay connects back over a private Unix socket, and the host starts the provider in the Box.
 */
export async function startProviderBoxRelay(options: ProviderBoxRelayOptions): Promise<ProviderBoxRelay> {
  const token = randomBytes(32).toString("hex")
  const socketPath = join(options.launchRoot, "relay.sock")
  const relayPath = join(options.launchRoot, "relay.mjs")
  const launcherPath = join(options.launchRoot, "provider")
  const processes = new Set<BoxProcess>()
  const sockets = new Set<Socket>()
  const handlers = new Set<Promise<void>>()
  const server: Server = createServer({ allowHalfOpen: true }, (socket) => {
    sockets.add(socket)
    socket.once("close", () => sockets.delete(socket))
    // A launcher can disconnect at any time. Socket errors close the connection and do not reach the host process.
    socket.on("error", () => socket.destroy())
    const handler = handleRelayConnection(socket, token, options, processes).catch(() => { socket.destroy() })
    handlers.add(handler)
    void handler.finally(() => handlers.delete(handler))
  })
  server.listen(socketPath)
  await once(server, "listening")
  try {
    await chmod(socketPath, 0o600)
    await writeFile(relayPath, relaySource(socketPath, token), { mode: 0o600 })
    await writeFile(launcherPath, `#!/bin/sh\nexec ${shellQuote(process.execPath)} ${shellQuote(relayPath)} "$@"\n`, { mode: 0o700 })
  }
  catch (error) {
    for (const socket of sockets) socket.destroy()
    await new Promise<void>(resolve => server.close(() => resolve())).catch(() => undefined)
    throw error
  }
  let closing: Promise<void> | undefined
  return {
    launcher: launcherPath,
    close() {
      return closing ??= (async () => {
        // BoxProcess.kill() may wait for a provider that traps SIGTERM. Keep the
        // relay bounded so the owning Box session can run its escalation path.
        const killing = Promise.all([...processes].map(child => child.kill().catch(() => undefined)))
        await Promise.race([killing, boundedRelayCleanup()])
        for (const socket of sockets) socket.destroy()
        await new Promise<void>(resolve => server.close(() => resolve()))
        await Promise.all([...handlers])
      })()
    },
  }
}

function boundedRelayCleanup() {
  return new Promise<void>(resolve => {
    const timer = setTimeout(resolve, relayCleanupTimeoutMs)
    timer.unref?.()
  })
}


async function handleRelayConnection(
  socket: Socket,
  token: string,
  options: ProviderBoxRelayOptions,
  processes: Set<BoxProcess>,
) {
  const { args, env, input } = await readRelayHeader(socket, token)
  const redact = (text: string) => options.box.omitDiagnosticOutput ? "[Box Home diagnostic output omitted]" : Object.values(options.box.environment ?? {}).filter((value): value is string => Boolean(value)).toSorted((left, right) => right.length - left.length)
    .reduce((safe, value) => safe.replaceAll(value, "[REDACTED]"), text)
  const boxCwd = options.box.session.cwd
  const workspacePath = options.box.workspace?.path
  const mirrorsLocalRoot = workspacePath === options.localRoot
  const mirrorsLocalCwd = workspacePath === options.localCwd
  // An authoritative Box cwd can point at a separate host checkout. In that
  // case provider paths are anchored at the local provider cwd, while the
  // process itself starts in the Box session cwd. Only a Box workspace that
  // mirrors localRoot can preserve a nested provider suffix.
  const mappingRoot = workspacePath === undefined || (!mirrorsLocalRoot && !mirrorsLocalCwd)
    ? options.localCwd || options.localRoot
    : workspacePath
  const mapPath = (value: string) => mappingRoot && (value === mappingRoot
    ? boxCwd
    : value.startsWith(`${mappingRoot}/`)
      ? `${boxCwd}${value.slice(mappingRoot.length)}`
      : undefined)
  const boxWorkingDirectory = mirrorsLocalRoot && options.localCwd !== undefined
    ? mapPath(options.localCwd)
    : boxCwd
  const textPathDelimiter = "[/\\\\\"'\\s,:;\\[\\]{}()?=#&|<>`]"
  const textPathLeftDelimiter = "[/\\\\\"'\\s,:;\\[\\]{}()?=#&|<>@`]"
  const mapTextPattern = mappingRoot
    ? new RegExp(`(^|${textPathLeftDelimiter})${escapeRegExp(mappingRoot)}(?=$|${textPathDelimiter})`, "g")
    : undefined
  const mapText = (value: string) => mapTextPattern
    ? value.replace(mapTextPattern, (_match, prefix: string) => `${prefix}${boxCwd}`)
    : value
  const selectedArgs = options.filterArgs ? options.filterArgs(args, mapPath) : [...args]
  let disconnected = socket.destroyed
  socket.once("close", () => {
    disconnected = true
  })
  let child: BoxProcess
  try {
    if (!boxWorkingDirectory) throw new Error("[vitehub] Agent Box provider cwd is outside the mapped provider checkout.")
    const environment = Object.fromEntries(Object.entries(options.environment(env)).map(([name, value]) => [name, mapText(value)]))
    child = await options.box.spawn(options.command, selectedArgs.map(mapText), {
      cwd: boxWorkingDirectory,
      env: environment,
    })
  }
  catch (error) {
    const message = redact(error instanceof Error ? error.message : String(error))
    await writeDiagnostic(options.diagnosticPath, { exitCode: 127, spawnError: message })
    socket.write(frame(frameStderr, Buffer.from(`${message}\n`)))
    socket.end(exitFrame(127))
    return
  }
  // The launcher can disconnect while a remote Box starts the process. Stop the process that nobody reads.
  if (disconnected) {
    await child.kill().catch(() => undefined)
    return
  }
  processes.add(child)
  let exited = false
  socket.once("close", () => {
    if (!exited) void child.kill().catch(() => undefined)
  })
  const stdin = child.stdin
  if (!stdin) {
    await child.kill().catch(() => undefined)
    processes.delete(child)
    const message = "[vitehub] Agent Box runtime does not forward process input."
    await writeDiagnostic(options.diagnosticPath, { exitCode: 127, spawnError: message })
    socket.write(frame(frameStderr, Buffer.from(`${message}\n`)))
    socket.end(exitFrame(127))
    return
  }
  const inputForwarding = new AbortController()
  const forwardInput = pipeRelayInput(socket, input, stdin, mapText, inputForwarding.signal)
  // A broken stdin transport can otherwise leave a provider blocked waiting for input.
  // Terminate the child so its wait settles and the relay can report the failure.
  void forwardInput.catch(() => child.kill().catch(() => undefined))
  let stderrBytes = 0
  let stderrTail = Buffer.alloc(0)
  const forward = (stream: ReadableStream<Uint8Array>, type: number) => forwardStream(stream, async (chunk) => {
    if (type === frameStderr) {
      stderrBytes += chunk.byteLength
      stderrTail = Buffer.concat([stderrTail, chunk]).subarray(-stderrTailBytes)
    }
    if (socket.destroyed || socket.write(frame(type, chunk))) return
    const draining = new AbortController()
    const onClose = () => draining.abort()
    socket.once("close", onClose)
    try {
      await once(socket, "drain", { signal: draining.signal })
    }
    catch (error) {
      if (!socket.destroyed) throw error
    }
    finally {
      socket.off("close", onClose)
    }
  })
  // The provider can exit while the provider runtime keeps its input open.
  // Input forwarding stops at exit, so the relay does not wait for input that the provider no longer reads.
  const [, , exit] = await Promise.all([
    forward(child.stdout, frameStdout),
    forward(child.stderr, frameStderr),
    child.wait().finally(() => inputForwarding.abort()),
  ])
  exited = true
  processes.delete(child)
  if (exit.code !== 0) {
    const diagnostic: Record<string, unknown> = {
      exitCode: exit.code,
      stderr: redact(stderrTail.toString("utf8")),
      stderrBytes,
    }
    if (stderrBytes > stderrTail.byteLength) diagnostic.stderrTruncated = true
    await writeDiagnostic(options.diagnosticPath, diagnostic)
  }
  if (!socket.destroyed) socket.end(exitFrame(exit.code))
}

async function readRelayHeader(socket: Socket, token: string) {
  const [line, input] = await new Promise<[Buffer, Buffer]>((resolve, reject) => {
    let buffered = Buffer.alloc(0)
    const cleanup = () => {
      socket.off("data", onData)
      socket.off("end", onEnd)
      socket.off("close", onEnd)
      socket.off("error", reject)
    }
    const onData = (chunk: Buffer) => {
      buffered = Buffer.concat([buffered, chunk])
      const newline = buffered.indexOf(10)
      if (newline === -1 && buffered.byteLength <= 4 * 1024 * 1024) return
      cleanup()
      socket.pause()
      if (newline === -1) reject(invalidRelayConnection())
      else resolve([buffered.subarray(0, newline), buffered.subarray(newline + 1)])
    }
    const onEnd = () => {
      cleanup()
      reject(invalidRelayConnection())
    }
    socket.on("data", onData)
    // A launcher that disconnects before it sends the header emits 'close' without 'end'.
    socket.once("end", onEnd)
    socket.once("close", onEnd)
    socket.once("error", reject)
  })
  let header: unknown
  try {
    header = JSON.parse(line.toString("utf8"))
  }
  catch {
    throw invalidRelayConnection()
  }
  if (!isRuntimeRecord(header)) throw invalidRelayConnection()
  const received = Reflect.get(header, "token")
  const args = Reflect.get(header, "args")
  const env = Reflect.get(header, "env")
  if (!hasRuntimeType(received, "string") || !sameToken(received, token)) throw invalidRelayConnection()
  if (!Array.isArray(args) || !args.every(arg => hasRuntimeType(arg, "string"))) throw invalidRelayConnection()
  if (!isRuntimeRecord(env)) throw invalidRelayConnection()
  const environment: Record<string, string> = {}
  for (const [name, value] of Object.entries(env)) if (hasRuntimeType(value, "string")) environment[name] = value
  return { args: args.map(String), env: environment, input }
}

function invalidRelayConnection() {
  return agentDiagnostics.AGENT_R0953({ message: "[vitehub] Agent Box relay received an invalid connection." })
}

function sameToken(received: string, expected: string) {
  const left = Buffer.from(received)
  const right = Buffer.from(expected)
  return left.byteLength === right.byteLength && timingSafeEqual(left, right)
}

/** Forward provider input line by line so local paths map to Box paths without splitting a path. */
async function pipeRelayInput(
  socket: Socket,
  initial: Buffer,
  stdin: WritableStream<Uint8Array>,
  mapText: (value: string) => string,
  signal: AbortSignal,
) {
  const writer = stdin.getWriter()
  let pending = ""
  const decoder = new TextDecoder()
  const encoder = new TextEncoder()
  const push = async (chunk: Uint8Array) => {
    pending += decoder.decode(chunk, { stream: true })
    const newline = pending.lastIndexOf("\n")
    if (newline === -1) return
    const complete = pending.slice(0, newline + 1)
    pending = pending.slice(newline + 1)
    await writer.write(encoder.encode(mapText(complete)))
  }
  let stop: (() => void) | undefined
  const stopped = new Promise<void>((resolve) => {
    stop = resolve
  })
  const onAbort = () => {
    stop?.()
    // Pending writes to a process that exited can wait forever. Abort the writer so they settle.
    void writer.abort(signal.reason).catch(() => undefined)
  }
  if (signal.aborted) onAbort()
  else signal.addEventListener("abort", onAbort, { once: true })
  let queue = Promise.resolve()
  let fail: ((error: unknown) => void) | undefined
  const onData = (chunk: Buffer) => {
    socket.pause()
    queue = queue.then(() => push(chunk)).then(() => {
      if (!signal.aborted) socket.resume()
    })
    queue.catch(error => fail?.(error))
  }
  try {
    if (initial.byteLength) await Promise.race([push(initial), stopped])
    // The relay can send its header, input, and end of input before the Box process starts.
    // In that case the socket already emitted 'end' while readRelayHeader held it paused.
    if (!signal.aborted && !socket.readableEnded && !socket.destroyed) {
      await Promise.race([stopped, new Promise<void>((resolve, reject) => {
        fail = reject
        socket.on("data", onData)
        socket.once("end", () => queue.then(resolve, reject))
        socket.once("close", () => queue.then(resolve, reject))
        socket.once("error", reject)
        socket.resume()
      })])
    }
    if (signal.aborted) return
    await Promise.race([queue, stopped])
    if (signal.aborted) return
    pending += decoder.decode()
    if (pending) await writer.write(encoder.encode(mapText(pending)))
    await writer.close()
  }
  catch (error) {
    await writer.abort(error).catch(() => undefined)
    throw error
  }
  finally {
    signal.removeEventListener("abort", onAbort)
    socket.off("data", onData)
    // Discard input that arrives after the process exited, so the socket can finish closing.
    if (signal.aborted && !socket.destroyed) socket.resume()
  }
}

async function forwardStream(stream: ReadableStream<Uint8Array>, write: (chunk: Uint8Array) => void | Promise<void>) {
  const reader = stream.getReader()
  try {
    while (true) {
      const { done, value } = await reader.read()
      if (done) return
      await write(value)
    }
  }
  finally {
    reader.releaseLock()
  }
}

function frame(type: number, payload: Uint8Array) {
  const header = Buffer.alloc(5)
  header.writeUInt8(type, 0)
  header.writeUInt32BE(payload.byteLength, 1)
  return Buffer.concat([header, payload])
}

function exitFrame(code: number) {
  const payload = Buffer.alloc(4)
  payload.writeInt32BE(code, 0)
  return frame(frameExit, payload)
}

async function writeDiagnostic(path: string, diagnostic: Record<string, unknown>) {
  await writeFile(path, JSON.stringify(diagnostic), { mode: 0o600 }).catch(() => undefined)
}

/** Select the provider runtime environment for the Box process. */
export function providerBoxEnvironment(options: {
  /** Names resolved from driver.env. They are always forwarded. */
  explicit: readonly string[]
  /** Host process environment. Names from it stay on the host unless driver.env names them. */
  host: Readonly<Record<string, string | undefined>>
  /** Environment prepared by ViteHub before the provider runtime starts. */
  prepared: Readonly<Record<string, string | undefined>>
  /** Environment received by the relay from the provider runtime. */
  received: Readonly<Record<string, string>>
}): Record<string, string> {
  const explicit = new Set(options.explicit)
  const selected: Record<string, string> = {}
  for (const [name, value] of Object.entries(options.received)) {
    if (!environmentNamePattern.test(name) || boxRuntimeEnvironmentKeys.has(name)) continue
    // Values added by the provider runtime, such as the MCP bearer token, are forwarded.
    // Host values, such as PATH, stay on the host unless driver.env names them.
    if (name === "T3_MCP_BEARER_TOKEN" || explicit.has(name) || (options.prepared[name] === undefined && options.host[name] === undefined)) selected[name] = value
  }
  return selected
}

function relaySource(socketPath: string, token: string) {
  return `import { connect } from "node:net"
const socket = connect(${JSON.stringify(socketPath)})
let exitCode = 1
let buffered = Buffer.alloc(0)
let forwarding = Promise.resolve()
socket.on("connect", () => {
  socket.write(JSON.stringify({ token: ${JSON.stringify(token)}, args: process.argv.slice(2), env: process.env }) + "\\n")
  process.stdin.pipe(socket)
})
socket.on("data", (chunk) => {
  socket.pause()
  buffered = Buffer.concat([buffered, chunk])
  forwarding = consumeFrames().then(() => socket.resume(), () => socket.destroy())
})
async function consumeFrames() {
  while (buffered.length >= 5) {
    const length = buffered.readUInt32BE(1)
    if (buffered.length < 5 + length) break
    const type = buffered[0]
    const payload = buffered.subarray(5, 5 + length)
    buffered = buffered.subarray(5 + length)
    if (type === ${frameStdout}) await writeOutput(process.stdout, payload)
    else if (type === ${frameStderr}) await writeOutput(process.stderr, payload)
    else if (type === ${frameExit}) exitCode = payload.readInt32BE(0)
  }
}
function writeOutput(stream, payload) {
  return new Promise((resolve, reject) => stream.write(payload, (error) => error ? reject(error) : resolve()))
}
socket.on("error", (error) => {
  process.stderr.write("[vitehub] Agent Box relay failed: " + error.message + "\\n")
})
socket.on("close", () => {
  process.stdin.unpipe(socket)
  process.stdin.destroy()
  void forwarding.then(() => { process.exitCode = exitCode })
})
`
}

function escapeRegExp(value: string) {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&")
}

function shellQuote(value: string) {
  return `'${value.replaceAll("'", `'"'"'`)}'`
}
