export const consoleAppConfig = {
  colors: {
    error: "red",
    info: "sky",
    neutral: "zinc",
    primary: "blue",
    success: "emerald",
    warning: "amber",
  },
  icons: {
    arrowDown: "i-lucide-arrow-down",
    arrowLeft: "i-lucide-arrow-left",
    arrowRight: "i-lucide-arrow-right",
    arrowUp: "i-lucide-arrow-up",
    caution: "i-lucide-triangle-alert",
    check: "i-lucide-check",
    chevronDown: "i-lucide-chevron-down",
    chevronLeft: "i-lucide-chevron-left",
    chevronRight: "i-lucide-chevron-right",
    chevronUp: "i-lucide-chevron-up",
    close: "i-lucide-x",
    copy: "i-lucide-copy",
    copyCheck: "i-lucide-check",
    dark: "i-lucide-moon",
    drag: "i-lucide-grip-vertical",
    ellipsis: "i-lucide-ellipsis",
    error: "i-lucide-circle-alert",
    external: "i-lucide-external-link",
    eye: "i-lucide-eye",
    eyeOff: "i-lucide-eye-off",
    file: "i-lucide-file",
    folder: "i-lucide-folder",
    folderOpen: "i-lucide-folder-open",
    hash: "i-lucide-hash",
    info: "i-lucide-info",
    light: "i-lucide-sun",
    loading: "i-lucide-loader-circle",
    menu: "i-lucide-menu",
    minus: "i-lucide-minus",
    panelClose: "i-lucide-panel-left-close",
    panelOpen: "i-lucide-panel-left-open",
    plus: "i-lucide-plus",
    reload: "i-lucide-refresh-cw",
    search: "i-lucide-search",
    stop: "i-lucide-square",
    star: "i-lucide-star",
    success: "i-lucide-circle-check",
    system: "i-lucide-monitor",
    tip: "i-lucide-lightbulb",
    upload: "i-lucide-upload",
    warning: "i-lucide-triangle-alert",
  },
  button: {
    defaultVariants: {
      size: "sm",
    },
    slots: {
      base: "rounded-md font-normal",
      leadingIcon: "size-4 opacity-80",
      trailingIcon: "size-3.5 opacity-75",
    },
  },
  dashboardNavbar: {
    slots: {
      root: "h-11 px-3 sm:px-4",
      title: "text-sm font-medium",
      icon: "size-4 opacity-80",
      left: "gap-1.5",
      right: "gap-1.5",
    },
  },
  dashboardSearchButton: {
    defaultVariants: {
      size: "sm",
    },
    slots: {
      base: "h-9 rounded-md px-2.5 text-sm",
      leadingIcon: "size-4 opacity-80",
      trailing: "text-[11px] opacity-75",
    },
  },
  empty: {
    slots: {
      root: "gap-3 p-5",
      title: "text-sm font-medium",
      description: "text-xs leading-5",
      actions: "mt-1",
    },
  },
  input: {
    defaultVariants: {
      size: "sm",
    },
    slots: {
      leadingIcon: "size-4 opacity-80",
      trailingIcon: "size-3.5 opacity-75",
    },
  },
  pageCard: {
    slots: {
      container: "gap-0 p-4",
      leading: "mb-3 size-8 rounded-md bg-elevated/60",
      leadingIcon: "size-4 text-muted opacity-80",
      title: "text-sm font-medium",
      description: "mt-1 text-xs/5 text-muted",
    },
  },
  select: {
    defaultVariants: {
      size: "sm",
    },
    slots: {
      leadingIcon: "size-4 opacity-80",
      trailingIcon: "size-3.5 opacity-75",
      itemLeadingIcon: "size-4 opacity-80",
      itemTrailingIcon: "size-3.5 opacity-75",
    },
  },
  table: {
    slots: {
      th: "h-8 px-2.5 py-1.5 text-[10px] font-medium uppercase tracking-[.08em] text-muted",
      td: "h-8 px-2.5 py-1.5 text-[11px] text-toned",
    },
  },
};
