import assert from "node:assert/strict"
import { randomUUID } from "node:crypto"
import { parseArgs } from "node:util"

import { type FetchOptions, ofetch } from "ofetch"

const providers = ["cloudflare", "vercel"] as const
const frameworks = ["nitro", "vite"] as const
const expectedWorkspaceProviders = {
  cloudflare: "memory",
  vercel: "memory",
} as const
const liveOnlyMessage = "Workspace e2e requires a deployed app: pnpm --dir packages/workspace test:e2e --mode live --provider cloudflare|vercel --framework nitro|vite --url <url>"

type Provider = typeof providers[number]
type Framework = typeof frameworks[number]

const log = (message: string) => console.log(`[e2e] ${message}`)

async function retry(label: string, run: () => Promise<void>) {
  let lastError: unknown
  for (let attempt = 1; attempt <= 10; attempt++) {
    try {
      return await run()
    }
    catch (error) {
      lastError = error
      if (attempt < 10) {
        log(`${label} retry ${attempt}/9`)
        await new Promise(resolve => setTimeout(resolve, 3000))
      }
    }
  }
  throw lastError
}

async function runLive(url: string, provider: Provider, framework: Framework) {
  const request = (path: string, options?: FetchOptions) => ofetch(path, { baseURL: url, ...options })
  const expectedHeading = framework === "nitro" ? "Nitro playground workspace" : "Vite playground workspace"
  const writePath = `generated/${provider}-${framework}-${randomUUID()}.md`
  const writeContent = `Generated by ${provider} ${framework} workspace e2e\n`

  log(`live ${provider} ${framework} -> ${url}`)

  await retry(`${provider} workspace read`, async () => {
    const result = await request("/api/workspace")
    assert.equal(result.ok, true)
    assert.equal(result.provider, expectedWorkspaceProviders[provider])
    assert.match(result.readme, new RegExp(expectedHeading))
    assert.ok(result.files.some((entry: { path?: string }) => entry.path === "README.md"))
    assert.ok(result.markdown.some((entry: { path?: string }) => entry.path === "README.md"))
  })

  await retry(`${provider} workspace write`, async () => {
    const result = await request("/api/workspace/write", {
      body: JSON.stringify({
        content: writeContent,
        path: writePath,
      }),
      headers: { "content-type": "application/json" },
      method: "POST",
    })

    assert.equal(result.ok, true)
    assert.equal(result.provider, expectedWorkspaceProviders[provider])
    assert.ok(result.snapshot?.id)
    assert.ok(result.committedSnapshot?.id)
    assert.equal(result.readBack, writeContent)
    assert.ok(result.diff.entries.some((entry: { path?: string, type?: string }) => entry.path === writePath && entry.type === "added"))
  })

  if (expectedWorkspaceProviders[provider] !== "memory") {
    await retry(`${provider} workspace fresh read after write`, async () => {
      const result = await request(`/api/workspace/read-fresh?path=${encodeURIComponent(writePath)}`)
      assert.equal(result.ok, true)
      assert.equal(result.provider, expectedWorkspaceProviders[provider])
      assert.equal(result.path, writePath)
      assert.equal(result.readBack, writeContent)
    })
  }

  log(`live ${provider} ${framework} ok`)
}

const { values } = parseArgs({
  options: {
    framework: { type: "string" },
    mode: { type: "string" },
    provider: { type: "string" },
    url: { type: "string" },
  },
  strict: true,
})

const mode = values.mode ?? "local"
const provider = values.provider as Provider | undefined
const framework = values.framework as Framework | undefined

if (mode !== "live")
  throw new TypeError(liveOnlyMessage)
assert.ok(values.url, "--url required for live mode")
assert.ok(provider && providers.includes(provider), "--provider required for live mode")
assert.ok(framework && frameworks.includes(framework), "--framework required for live mode")

await runLive(values.url, provider, framework)
