import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { parseArgs } from "node:util";

import { ofetch } from "ofetch";

const providers = ["cloudflare", "vercel"];
const expectedWorkspaceProviders = {
  cloudflare: "memory",
  vercel: "vercel-blob",
};
const liveOnlyMessage =
  "Workspace e2e requires a deployed app: vp run workspace:e2e --mode live --provider cloudflare|vercel --url <url>";

const log = (message) => console.log(`[e2e] ${message}`);

async function retry(label, run) {
  let lastError;
  for (let attempt = 1; attempt <= 10; attempt++) {
    try {
      return await run();
    } catch (error) {
      lastError = error;
      if (attempt < 10) {
        log(`${label} retry ${attempt}/9`);
        await new Promise((resolve) => setTimeout(resolve, 3000));
      }
    }
  }
  throw lastError;
}

async function runLive(url, provider) {
  const request = (path, options) => ofetch(path, { baseURL: url, ...options });
  const expectedHeading = "Vite playground workspace";
  const writePath = `generated/${provider}-${randomUUID()}.md`;
  const writeContent = `Generated by ${provider} workspace e2e\n`;

  log(`live ${provider} -> ${url}`);

  await retry(`${provider} workspace read`, async () => {
    const result = await request("/api/workspace");
    assert.equal(result.ok, true);
    assert.equal(result.provider, expectedWorkspaceProviders[provider]);
    assert.match(result.readme, new RegExp(expectedHeading));
    assert.ok(result.files.some((entry) => entry.path === "README.md"));
    assert.ok(result.markdown.some((entry) => entry.path === "README.md"));
  });

  await retry(`${provider} workspace write`, async () => {
    const result = await request("/api/workspace/write", {
      body: JSON.stringify({
        content: writeContent,
        path: writePath,
      }),
      headers: { "content-type": "application/json" },
      method: "POST",
    });

    assert.equal(result.ok, true);
    assert.equal(result.provider, expectedWorkspaceProviders[provider]);
    assert.equal(result.path, writePath);
    assert.equal(result.readBack, writeContent);
  });

  if (expectedWorkspaceProviders[provider] !== "memory") {
    await retry(`${provider} workspace fresh read after write`, async () => {
      const result = await request(
        `/api/workspace/read-fresh?path=${encodeURIComponent(writePath)}`,
      );
      assert.equal(result.ok, true);
      assert.equal(result.provider, expectedWorkspaceProviders[provider]);
      assert.equal(result.path, writePath);
      assert.equal(result.readBack, writeContent);
    });
  }

  log(`live ${provider} ok`);
}

const { values } = parseArgs({
  options: {
    mode: { type: "string" },
    provider: { type: "string" },
    url: { type: "string" },
  },
  strict: true,
});

const mode = values.mode ?? "local";
const provider = values.provider;

if (mode !== "live" && mode !== "local") throw new TypeError(liveOnlyMessage);
assert.ok(values.url, `--url required for ${mode} mode`);
assert.ok(provider && providers.includes(provider), `--provider required for ${mode} mode`);

await runLive(values.url, provider);
