import { defineConfig } from "vite-plus"

export default defineConfig({
  pack: {
    tsconfig: "tsconfig.build.json",
    deps: {
      neverBundle: ["vite", /^@vite-hub\//],
      onlyBundle: false,
    },
    plugins: [{
      name: "vite-hub-env-config-declarations",
      generateBundle(_options, bundle) {
        const chunk = bundle["index.d.ts"]
        if (chunk?.type === "chunk") chunk.code = `import "@vite-hub/env/vite";\n${chunk.code}`
      },
    }],
    entry: [
      "src/_internal/agent.ts",
      "src/_internal/agent/cloudflare.ts",
      "src/_internal/agent/cloudflare/state.ts",
      "src/_internal/agent/runtime/workflow.ts",
      "src/_internal/agent/server.ts",
      "src/_internal/agent/server/internal.ts",
      "src/_internal/agent/server/workspace.ts",
      "src/_internal/agent/state/sqlite.ts",
      "src/_internal/blob.ts",
      "src/_internal/blob/runtime/state.ts",
      "src/_internal/kv.ts",
      "src/_internal/kv/runtime/disabled-upstash.ts",
      "src/_internal/markdown-template.ts",
      "src/_internal/schedule.ts",
      "src/_internal/schedule/runtime.ts",
      "src/_internal/schedule/runtime/driver.ts",
      "src/_internal/schedule/runtime/process.ts",
      "src/_internal/schedule/runtime/static.ts",
      "src/_internal/sandbox/runtime/state.ts",
      "src/_internal/workflow.ts",
      "src/_internal/workflow/runtime/execute.ts",
      "src/_internal/workflow/runtime/state.ts",
      "src/_internal/workspace.ts",
      "src/_internal/workspace/internal/runtime/hosted.ts",
      "src/_internal/workspace/internal/runtime/hosted-vercel-blob.ts",
      "src/_internal/workspace/runtime.ts",
      "src/agent.ts",
      "src/agent/capabilities.ts",
      "src/agent/channels.ts",
      "src/auth.ts",
      "src/auth/server.ts",
      "src/bin.ts",
      "src/blob.ts",
      "src/box.ts",
      "src/database.ts",
      "src/database/drizzle.ts",
      "src/email.ts",
      "src/email/markdown.ts",
      "src/email/server.ts",
      "src/env.ts",
      "src/env/presets.ts",
      "src/env/schema.ts",
      "src/env/secret.ts",
      "src/env/server.ts",
      "src/index.ts",
      "src/kv.ts",
      "src/queue.ts",
      "src/runtime.ts",
      "src/sandbox.ts",
      "src/schedule.ts",
      "src/schedule/runtime.ts",
      "src/shell.ts",
      "src/shell/workspace.ts",
      "src/source.ts",
      "src/workflow.ts",
      "src/workspace.ts",
      "src/workspace/runtime.ts",
    ],
    exports: {
      exclude: ["bin"],
      bin: {
        "vite-hub": "src/bin.ts",
        vitehub: "src/bin.ts",
      },
      inlinedDependencies: false,
    },
    outExtensions: () => ({
      dts: ".d.ts",
      js: ".js",
    }),
    publint: true,
  },
})
