import { defineDiagnostics } from "nostics"

const dynamicError = {
  why: ({ message }: { message?: unknown }) => message === undefined ? "" : String(message),
}

// Each code identifies one ViteHub failure site. Keep published codes stable.
export const workspaceErrorDiagnostics = /*#__PURE__*/ defineDiagnostics({
  docsBase: () => "https://vitehub.dev/docs/reference/errors-diagnostics",
  codes: {
    WORKSPACE_R0067: dynamicError,
    WORKSPACE_R0068: dynamicError,
    WORKSPACE_R0001: dynamicError,
    WORKSPACE_R0002: dynamicError,
    WORKSPACE_R0003: dynamicError,
    WORKSPACE_B0001: dynamicError,
    WORKSPACE_B0002: dynamicError,
    WORKSPACE_R0004: dynamicError,
    WORKSPACE_R0005: dynamicError,
    WORKSPACE_R0006: dynamicError,
    WORKSPACE_R0007: dynamicError,
    WORKSPACE_R0008: dynamicError,
    WORKSPACE_R0009: dynamicError,
    WORKSPACE_R0010: dynamicError,
    WORKSPACE_R0011: dynamicError,
    WORKSPACE_R0012: dynamicError,
    WORKSPACE_R0013: dynamicError,
    WORKSPACE_R0014: dynamicError,
    WORKSPACE_C0001: dynamicError,
    WORKSPACE_C0002: dynamicError,
    WORKSPACE_R0015: dynamicError,
    WORKSPACE_R0016: dynamicError,
    WORKSPACE_R0017: dynamicError,
    WORKSPACE_R0018: dynamicError,
    WORKSPACE_R0019: dynamicError,
    WORKSPACE_R0020: dynamicError,
    WORKSPACE_R0021: dynamicError,
    WORKSPACE_R0022: dynamicError,
    WORKSPACE_R0023: dynamicError,
    WORKSPACE_R0024: dynamicError,
    WORKSPACE_R0025: dynamicError,
    WORKSPACE_R0026: dynamicError,
    WORKSPACE_R0027: dynamicError,
    WORKSPACE_R0028: dynamicError,
    WORKSPACE_R0029: dynamicError,
    WORKSPACE_R0030: dynamicError,
    WORKSPACE_R0031: dynamicError,
    WORKSPACE_R0032: dynamicError,
    WORKSPACE_R0033: dynamicError,
    WORKSPACE_R0034: dynamicError,
    WORKSPACE_R0035: dynamicError,
    WORKSPACE_R0036: dynamicError,
    WORKSPACE_R0037: dynamicError,
    WORKSPACE_R0038: dynamicError,
    WORKSPACE_R0039: dynamicError,
    WORKSPACE_R0040: dynamicError,
    WORKSPACE_R0041: dynamicError,
    WORKSPACE_R0042: dynamicError,
    WORKSPACE_R0043: dynamicError,
    WORKSPACE_R0044: dynamicError,
    WORKSPACE_R0045: dynamicError,
    WORKSPACE_C0003: dynamicError,
    WORKSPACE_C0004: dynamicError,
    WORKSPACE_C0005: dynamicError,
    WORKSPACE_C0006: dynamicError,
    WORKSPACE_C0007: dynamicError,
    WORKSPACE_R0046: dynamicError,
    WORKSPACE_R0047: dynamicError,
    WORKSPACE_R0048: dynamicError,
    WORKSPACE_R0049: dynamicError,
    WORKSPACE_R0050: dynamicError,
    WORKSPACE_R0051: dynamicError,
    WORKSPACE_R0052: dynamicError,
    WORKSPACE_R0053: dynamicError,
    WORKSPACE_R0054: dynamicError,
    WORKSPACE_R0055: dynamicError,
    WORKSPACE_R0056: dynamicError,
    WORKSPACE_R0057: dynamicError,
    WORKSPACE_R0058: dynamicError,
    WORKSPACE_R0059: dynamicError,
    WORKSPACE_R0060: dynamicError,
    WORKSPACE_R0061: dynamicError,
    WORKSPACE_R0062: dynamicError,
    WORKSPACE_R0063: dynamicError,
    WORKSPACE_R0064: dynamicError,
    WORKSPACE_R0065: dynamicError,
    WORKSPACE_R0066: dynamicError,
  },
})
