// Generated by scripts/generate-google.ts from the Gmail API Discovery document, revision 20260921. Do not edit.

/** Auto-forwarding settings for an account. */
export interface GmailAutoForwarding {
  /** Whether all incoming mail is automatically forwarded to another address. */
  enabled?: boolean
  /** The state that a message should be left in after it has been forwarded. */
  disposition?: "dispositionUnspecified" | "leaveInInbox" | "archive" | "trash" | "markRead"
  /** Email address to which all incoming messages are forwarded. */
  emailAddress?: string
}

export interface GmailBatchDeleteMessagesRequest {
  /** The IDs of the messages to delete. */
  ids?: Array<string>
}

export interface GmailBatchModifyMessagesRequest {
  /** A list of label IDs to remove from messages. */
  removeLabelIds?: Array<string>
  /** A list of label IDs to add to messages. */
  addLabelIds?: Array<string>
  /** The IDs of the messages to modify. */
  ids?: Array<string>
  /** A list of Classification Label values to add. */
  addClassificationLabels?: Array<GmailClassificationLabelValue>
  /** A list of Classification Label values to remove from messages. */
  removeClassificationLabelIds?: Array<string>
}

/** Field values for a classification label. */
export interface GmailClassificationLabelFieldValue {
  /** Required. */
  fieldId: string
  /** Selection choice ID for the selection option. */
  selection?: string
}

/** Classification Labels applied to the email message. */
export interface GmailClassificationLabelValue {
  /** Required. */
  labelId: string
  /** Field values for the given classification label ID. */
  fields?: Array<GmailClassificationLabelFieldValue>
}

/** The client-side encryption (CSE) configuration for the email address of an authenticated user. */
export interface GmailCseIdentity {
  /** If a key pair is associated, the ID of the key pair, CseKeyPair. */
  primaryKeyPairId?: string
  /** The configuration of a CSE identity that uses different key pairs for signing and encryption. */
  signAndEncryptKeyPairs?: GmailSignAndEncryptKeyPairs
  /** The email address for the sending identity. */
  emailAddress?: string
}

/** A client-side encryption S/MIME key pair, which is comprised of a public key, its certificate chain, and metadata for its paired private key. */
export interface GmailCseKeyPair {
  /** Output only. */
  enablementState?: "stateUnspecified" | "enabled" | "disabled"
  /** Metadata for instances of this key pair's private key. */
  privateKeyMetadata?: Array<GmailCsePrivateKeyMetadata>
  /** Output only. */
  pem?: string
  /** Output only. */
  keyPairId?: string
  /** Input only. */
  pkcs7?: string
  /** Output only. */
  subjectEmailAddresses?: Array<string>
  /** Output only. */
  disableTime?: string
}

/** Metadata for a private key instance. */
export interface GmailCsePrivateKeyMetadata {
  /** Metadata for a private key instance managed by an external key access control list service. */
  kaclsKeyMetadata?: GmailKaclsKeyMetadata
  /** Output only. */
  privateKeyMetadataId?: string
  /** Metadata for hardware keys. */
  hardwareKeyMetadata?: GmailHardwareKeyMetadata
}

/** Settings for a delegate. */
export interface GmailDelegate {
  /** The email address of the delegate. */
  delegateEmail?: string
  /** Indicates whether this address has been verified and can act as a delegate for the account. */
  verificationStatus?: "verificationStatusUnspecified" | "accepted" | "pending" | "rejected" | "expired"
}

/** Requests to turn off a client-side encryption key pair. */
export type GmailDisableCseKeyPairRequest = Record<string, never>

/** A draft email in the user's mailbox. */
export interface GmailDraft {
  /** The message content of the draft. */
  message?: GmailMessage
  /** The immutable ID of the draft. */
  id?: string
}

/** Requests to turn on a client-side encryption key pair. */
export type GmailEnableCseKeyPairRequest = Record<string, never>

/** Resource definition for Gmail filters. */
export interface GmailFilter {
  /** Matching criteria for the filter. */
  criteria?: GmailFilterCriteria
  /** Action that the filter performs. */
  action?: GmailFilterAction
  /** The server assigned ID of the filter. */
  id?: string
}

/** A set of actions to perform on a message. */
export interface GmailFilterAction {
  /** List of labels to add to the message. */
  addLabelIds?: Array<string>
  /** Email address that the message should be forwarded to. */
  forward?: string
  /** List of labels to remove from the message. */
  removeLabelIds?: Array<string>
}

/** Message matching criteria. */
export interface GmailFilterCriteria {
  /** Only return messages not matching the specified query. */
  negatedQuery?: string
  /** The sender's display name or email address. */
  from?: string
  /** The size of the entire RFC822 message in bytes, including all headers and attachments. */
  size?: number
  /** Only return messages matching the specified query. */
  query?: string
  /** Whether the response should exclude chats. */
  excludeChats?: boolean
  /** Case-insensitive phrase found in the message's subject. */
  subject?: string
  /** Whether the message has any attachment. */
  hasAttachment?: boolean
  /** How the message size in bytes should be in relation to the size field. */
  sizeComparison?: "unspecified" | "smaller" | "larger"
  /** The recipient's display name or email address. */
  to?: string
}

/** Settings for a forwarding address. */
export interface GmailForwardingAddress {
  /** An email address to which messages can be forwarded. */
  forwardingEmail?: string
  /** Indicates whether this address has been verified and is usable for forwarding. */
  verificationStatus?: "verificationStatusUnspecified" | "accepted" | "pending"
}

/** Metadata for hardware keys. */
export interface GmailHardwareKeyMetadata {
  /** Description about the hardware key. */
  description?: string
}

/** A record of a change to the user's mailbox. */
export interface GmailHistory {
  /** Labels removed from messages in this history record. */
  labelsRemoved?: Array<GmailHistoryLabelRemoved>
  /** Messages added to the mailbox in this history record. */
  messagesAdded?: Array<GmailHistoryMessageAdded>
  /** Labels added to messages in this history record. */
  labelsAdded?: Array<GmailHistoryLabelAdded>
  /** Messages deleted (not Trashed) from the mailbox in this history record. */
  messagesDeleted?: Array<GmailHistoryMessageDeleted>
  /** List of messages changed in this history record. */
  messages?: Array<GmailMessage>
  /** The mailbox sequence ID. */
  id?: string
}

export interface GmailHistoryLabelAdded {
  /** Label IDs added to the message. */
  labelIds?: Array<string>
  message?: GmailMessage
}

export interface GmailHistoryLabelRemoved {
  message?: GmailMessage
  /** Label IDs removed from the message. */
  labelIds?: Array<string>
}

export interface GmailHistoryMessageAdded {
  message?: GmailMessage
}

export interface GmailHistoryMessageDeleted {
  message?: GmailMessage
}

/** IMAP settings for an account. */
export interface GmailImapSettings {
  /** If this value is true, Gmail will immediately expunge a message when it is marked as deleted in IMAP. */
  autoExpunge?: boolean
  /** Whether IMAP is enabled for the account. */
  enabled?: boolean
  /** The action that will be executed on a message when it is marked as deleted and expunged from the last visible IMAP folder. */
  expungeBehavior?: "expungeBehaviorUnspecified" | "archive" | "trash" | "deleteForever"
  /** An optional limit on the number of messages that an IMAP folder may contain. */
  maxFolderSize?: number
}

/** Metadata for private keys managed by an external key access control list service. */
export interface GmailKaclsKeyMetadata {
  /** The URI of the key access control list service that manages the private key. */
  kaclsUri?: string
  /** Opaque data generated and used by the key access control list service. */
  kaclsData?: string
}

/** Labels are used to categorize messages and threads within the user's mailbox. */
export interface GmailLabel {
  /** The visibility of the label in the label list in the Gmail web interface. */
  labelListVisibility?: "labelShow" | "labelShowIfUnread" | "labelHide"
  /** The total number of threads with the label. */
  threadsTotal?: number
  /** The number of unread threads with the label. */
  threadsUnread?: number
  /** The number of unread messages with the label. */
  messagesUnread?: number
  /** The display name of the label. */
  name?: string
  /** The visibility of messages with this label in the message list in the Gmail web interface. */
  messageListVisibility?: "show" | "hide"
  /** The color to assign to the label. */
  color?: GmailLabelColor
  /** The immutable ID of the label. */
  id?: string
  /** The total number of messages with the label. */
  messagesTotal?: number
  /** The owner type for the label. */
  type?: "system" | "user"
}

export interface GmailLabelColor {
  /** The text color of the label, represented as hex string. */
  textColor?: string
  /** The background color represented as hex string #RRGGBB (ex #000000). */
  backgroundColor?: string
}

/** Language settings for an account. */
export interface GmailLanguageSettings {
  /** The language to display Gmail in, formatted as an RFC 3066 Language Tag (for example `en-GB`, `fr` or `ja` for British English, French, or Japanese respectively). */
  displayLanguage?: string
}

export interface GmailListCseIdentitiesResponse {
  /** One page of the list of CSE identities configured for the user. */
  cseIdentities?: Array<GmailCseIdentity>
  /** Pagination token to be passed to a subsequent ListCseIdentities call in order to retrieve the next page of identities. */
  nextPageToken?: string
}

export interface GmailListCseKeyPairsResponse {
  /** One page of the list of CSE key pairs installed for the user. */
  cseKeyPairs?: Array<GmailCseKeyPair>
  /** Pagination token to be passed to a subsequent ListCseKeyPairs call in order to retrieve the next page of key pairs. */
  nextPageToken?: string
}

/** Response for the ListDelegates method. */
export interface GmailListDelegatesResponse {
  /** List of the user's delegates (with any verification status). */
  delegates?: Array<GmailDelegate>
}

export interface GmailListDraftsResponse {
  /** Token to retrieve the next page of results in the list. */
  nextPageToken?: string
  /** List of drafts. */
  drafts?: Array<GmailDraft>
  /** Estimated total number of results. */
  resultSizeEstimate?: number
}

/** Response for the ListFilters method. */
export interface GmailListFiltersResponse {
  /** List of a user's filters. */
  filter?: Array<GmailFilter>
}

/** Response for the ListForwardingAddresses method. */
export interface GmailListForwardingAddressesResponse {
  /** List of addresses that may be used for forwarding. */
  forwardingAddresses?: Array<GmailForwardingAddress>
}

export interface GmailListHistoryResponse {
  /** The ID of the mailbox's current history record. */
  historyId?: string
  /** List of history records. */
  history?: Array<GmailHistory>
  /** Page token to retrieve the next page of results in the list. */
  nextPageToken?: string
}

export interface GmailListLabelsResponse {
  /** List of labels. */
  labels?: Array<GmailLabel>
}

export interface GmailListMessagesResponse {
  /** Token to retrieve the next page of results in the list. */
  nextPageToken?: string
  /** List of messages. */
  messages?: Array<GmailMessage>
  /** Estimated total number of results. */
  resultSizeEstimate?: number
}

/** Response for the ListSendAs method. */
export interface GmailListSendAsResponse {
  /** List of send-as aliases. */
  sendAs?: Array<GmailSendAs>
}

export interface GmailListSmimeInfoResponse {
  /** List of SmimeInfo. */
  smimeInfo?: Array<GmailSmimeInfo>
}

export interface GmailListThreadsResponse {
  /** List of threads. */
  threads?: Array<GmailThread>
  /** Page token to retrieve the next page of results in the list. */
  nextPageToken?: string
  /** Estimated total number of results. */
  resultSizeEstimate?: number
}

/** An email message. */
export interface GmailMessage {
  /** The ID of the last history record that modified this message. */
  historyId?: string
  /** List of IDs of labels applied to this message. */
  labelIds?: Array<string>
  /** A short part of the message text. */
  snippet?: string
  /** The entire email message in an RFC 2822 formatted and base64url encoded string. */
  raw?: string
  /** The immutable ID of the message. */
  id?: string
  /** Classification Label values on the message. */
  classificationLabelValues?: Array<GmailClassificationLabelValue>
  /** The ID of the thread the message belongs to. */
  threadId?: string
  /** Estimated size in bytes of the message. */
  sizeEstimate?: number
  /** The internal message creation timestamp (epoch ms), which determines ordering in the inbox. */
  internalDate?: string
  /** The parsed email structure in the message parts. */
  payload?: GmailMessagePart
}

/** A single MIME message part. */
export interface GmailMessagePart {
  /** The immutable ID of the message part. */
  partId?: string
  /** The message part body for this part, which may be empty for container MIME message parts. */
  body?: GmailMessagePartBody
  /** The child MIME message parts of this part. */
  parts?: Array<GmailMessagePart>
  /** List of headers on this message part. */
  headers?: Array<GmailMessagePartHeader>
  /** The MIME type of the message part. */
  mimeType?: string
  /** The filename of the attachment. */
  filename?: string
}

/** The body of a single MIME message part. */
export interface GmailMessagePartBody {
  /** The body data of a MIME message part as a base64url encoded string. */
  data?: string
  /** When present, contains the ID of an external attachment that can be retrieved in a separate `messages.attachments.get` request. */
  attachmentId?: string
  /** Number of bytes for the message part data (encoding notwithstanding). */
  size?: number
}

export interface GmailMessagePartHeader {
  /** The name of the header before the `:` separator. */
  name?: string
  /** The value of the header after the `:` separator. */
  value?: string
}

export interface GmailModifyMessageRequest {
  /** A list of classification label values to add. */
  addClassificationLabels?: Array<GmailClassificationLabelValue>
  /** A list of Classification Label values to remove from this message. */
  removeClassificationLabelIds?: Array<string>
  /** A list of IDs of labels to add to this message. */
  addLabelIds?: Array<string>
  /** A list IDs of labels to remove from this message. */
  removeLabelIds?: Array<string>
}

export interface GmailModifyThreadRequest {
  /** A list of IDs of labels to add to this thread. */
  addLabelIds?: Array<string>
  /** A list of IDs of labels to remove from this thread. */
  removeLabelIds?: Array<string>
}

/** Request to obliterate a CSE key pair. */
export type GmailObliterateCseKeyPairRequest = Record<string, never>

/** POP settings for an account. */
export interface GmailPopSettings {
  /** The range of messages which are accessible via POP. */
  accessWindow?: "accessWindowUnspecified" | "disabled" | "fromNowOn" | "allMail"
  /** The action that will be executed on a message after it has been fetched via POP. */
  disposition?: "dispositionUnspecified" | "leaveInInbox" | "archive" | "trash" | "markRead"
}

/** Profile for a Gmail user. */
export interface GmailProfile {
  /** The total number of messages in the mailbox. */
  messagesTotal?: number
  /** The user's email address. */
  emailAddress?: string
  /** The total number of threads in the mailbox. */
  threadsTotal?: number
  /** The ID of the mailbox's current history record. */
  historyId?: string
}

/** Settings associated with a send-as alias, which can be either the primary login address associated with the account or a custom "from" address. */
export interface GmailSendAs {
  /** Whether this address is selected as the default "From:" address in situations such as composing a new message or sending a vacation auto-reply. */
  isDefault?: boolean
  /** The email address that appears in the "From:" header for mail sent using this alias. */
  sendAsEmail?: string
  /** An optional HTML signature that is included in messages composed with this alias in the Gmail web UI. */
  signature?: string
  /** A name that appears in the "From:" header for mail sent using this alias. */
  displayName?: string
  /** Whether Gmail should treat this address as an alias for the user's primary email address. */
  treatAsAlias?: boolean
  /** An optional SMTP service that will be used as an outbound relay for mail sent using this alias. */
  smtpMsa?: GmailSmtpMsa
  /** An optional email address that is included in a "Reply-To:" header for mail sent using this alias. */
  replyToAddress?: string
  /** Whether this address is the primary address used to login to the account. */
  isPrimary?: boolean
  /** Indicates whether this address has been verified for use as a send-as alias. */
  verificationStatus?: "verificationStatusUnspecified" | "accepted" | "pending"
}

/** The configuration of a CSE identity that uses different key pairs for signing and encryption. */
export interface GmailSignAndEncryptKeyPairs {
  /** The ID of the CseKeyPair that signs outgoing mail. */
  signingKeyPairId?: string
  /** The ID of the CseKeyPair that encrypts signed outgoing mail. */
  encryptionKeyPairId?: string
}

/** An S/MIME email config. */
export interface GmailSmimeInfo {
  /** Whether this SmimeInfo is the default one for this user's send-as address. */
  isDefault?: boolean
  /** When the certificate expires (in milliseconds since epoch). */
  expiration?: string
  /** PEM formatted X509 concatenated certificate string (standard base64 encoding). */
  pem?: string
  /** The immutable ID for the SmimeInfo. */
  id?: string
  /** The S/MIME certificate issuer's common name. */
  issuerCn?: string
  /** PKCS#12 format containing a single private/public key pair and certificate chain. */
  pkcs12?: string
  /** Encrypted key password, when key is encrypted. */
  encryptedKeyPassword?: string
}

/** Configuration for communication with an SMTP service. */
export interface GmailSmtpMsa {
  /** The password that will be used for authentication with the SMTP service. */
  password?: string
  /** The protocol that will be used to secure communication with the SMTP service. */
  securityMode?: "securityModeUnspecified" | "none" | "ssl" | "starttls"
  /** The username that will be used for authentication with the SMTP service. */
  username?: string
  /** The hostname of the SMTP service. */
  host?: string
  /** The port of the SMTP service. */
  port?: number
}

/** A collection of messages representing a conversation. */
export interface GmailThread {
  /** The unique ID of the thread. */
  id?: string
  /** The ID of the last history record that modified this thread. */
  historyId?: string
  /** The list of messages in the thread. */
  messages?: Array<GmailMessage>
  /** A short part of the message text. */
  snippet?: string
}

/** Vacation auto-reply settings for an account. */
export interface GmailVacationSettings {
  /** An optional end time for sending auto-replies (epoch ms). */
  endTime?: string
  /** Response body in HTML format. */
  responseBodyHtml?: string
  /** Flag that determines whether responses are sent to recipients who are outside of the user's domain. */
  restrictToDomain?: boolean
  /** An optional start time for sending auto-replies (epoch ms). */
  startTime?: string
  /** Optional text to prepend to the subject line in vacation responses. */
  responseSubject?: string
  /** Flag that determines whether responses are sent to recipients who are not in the user's list of contacts. */
  restrictToContacts?: boolean
  /** Flag that controls whether Gmail automatically replies to messages. */
  enableAutoReply?: boolean
  /** Response body in plain text format. */
  responseBodyPlainText?: string
}

/** Set up or update a new push notification watch on this user's mailbox. */
export interface GmailWatchRequest {
  /** Filtering behavior of `labelIds list` specified. */
  labelFilterBehavior?: "include" | "exclude"
  /** List of label_ids to restrict notifications about. */
  labelIds?: Array<string>
  /** A fully qualified Google Cloud Pub/Sub API topic name to publish the events to. */
  topicName?: string
  /** Filtering behavior of `labelIds list` specified. */
  labelFilterAction?: "include" | "exclude"
}

/** Push notification watch response. */
export interface GmailWatchResponse {
  /** The ID of the mailbox's current history record. */
  historyId?: string
  /** When Gmail will stop sending notifications for mailbox updates (epoch millis). */
  expiration?: string
}

export interface GmailMethods {
  /** Creates a draft with the `DRAFT` label. */
  "users.drafts.create": {
    method: "POST"
    params: {
      /** The user's email address. */
      userId: string
    }
    body: GmailDraft
    response: GmailDraft
  }
  /** Immediately and permanently deletes the specified draft. */
  "users.drafts.delete": {
    method: "DELETE"
    params: {
      /** The ID of the draft to delete. */
      id: string
      /** The user's email address. */
      userId: string
    }
    body: never
    response: void
  }
  /** Gets the specified draft. */
  "users.drafts.get": {
    method: "GET"
    params: {
      /** The user's email address. */
      userId: string
      /** The ID of the draft to retrieve. */
      id: string
      /** The format to return the draft in. */
      format?: "minimal" | "full" | "raw" | "metadata"
    }
    body: never
    response: GmailDraft
  }
  /** Lists the drafts in the user's mailbox. */
  "users.drafts.list": {
    method: "GET"
    params: {
      /** Include drafts from `SPAM` and `TRASH` in the results. */
      includeSpamTrash?: boolean
      /** Maximum number of drafts to return. */
      maxResults?: number
      /** The user's email address. */
      userId: string
      /** Page token to retrieve a specific page of results in the list. */
      pageToken?: string
      /** Only return draft messages matching the specified query. */
      q?: string
    }
    body: never
    response: GmailListDraftsResponse
  }
  /** Sends the specified, existing draft to the recipients in the `To`, `Cc`, and `Bcc` headers. */
  "users.drafts.send": {
    method: "POST"
    params: {
      /** The user's email address. */
      userId: string
    }
    body: GmailDraft
    response: GmailMessage
  }
  /** Replaces a draft's content. */
  "users.drafts.update": {
    method: "PUT"
    params: {
      /** The user's email address. */
      userId: string
      /** The ID of the draft to update. */
      id: string
    }
    body: GmailDraft
    response: GmailDraft
  }
  /** Gets the current user's Gmail profile. */
  "users.getProfile": {
    method: "GET"
    params: {
      /** The user's email address. */
      userId: string
    }
    body: never
    response: GmailProfile
  }
  /** Lists the history of all changes to the given mailbox. */
  "users.history.list": {
    method: "GET"
    params: {
      /** Only return messages with a label matching the ID. */
      labelId?: string
      /** Page token to retrieve a specific page of results in the list. */
      pageToken?: string
      /** Required. */
      startHistoryId: string
      /** The user's email address. */
      userId: string
      /** History types to be returned by the function */
      historyTypes?: Array<"messageAdded" | "messageDeleted" | "labelAdded" | "labelRemoved">
      /** Maximum number of history records to return. */
      maxResults?: number
    }
    body: never
    response: GmailListHistoryResponse
  }
  /** Creates a label. */
  "users.labels.create": {
    method: "POST"
    params: {
      /** The user's email address. */
      userId: string
    }
    body: GmailLabel
    response: GmailLabel
  }
  /** Immediately and permanently deletes the specified label and removes it from any messages and threads that it's applied to. */
  "users.labels.delete": {
    method: "DELETE"
    params: {
      /** The user's email address. */
      userId: string
      /** The ID of the label to delete. */
      id: string
    }
    body: never
    response: void
  }
  /** Gets the specified label. */
  "users.labels.get": {
    method: "GET"
    params: {
      /** The user's email address. */
      userId: string
      /** The ID of the label to retrieve. */
      id: string
    }
    body: never
    response: GmailLabel
  }
  /** Lists all labels in the user's mailbox. */
  "users.labels.list": {
    method: "GET"
    params: {
      /** The user's email address. */
      userId: string
    }
    body: never
    response: GmailListLabelsResponse
  }
  /** Patch the specified label. */
  "users.labels.patch": {
    method: "PATCH"
    params: {
      /** The user's email address. */
      userId: string
      /** The ID of the label to update. */
      id: string
    }
    body: GmailLabel
    response: GmailLabel
  }
  /** Updates the specified label. */
  "users.labels.update": {
    method: "PUT"
    params: {
      /** The ID of the label to update. */
      id: string
      /** The user's email address. */
      userId: string
    }
    body: GmailLabel
    response: GmailLabel
  }
  /** Gets the specified message attachment. */
  "users.messages.attachments.get": {
    method: "GET"
    params: {
      /** The ID of the message containing the attachment. */
      messageId: string
      /** The ID of the attachment. */
      id: string
      /** The user's email address. */
      userId: string
    }
    body: never
    response: GmailMessagePartBody
  }
  /** Deletes many messages by message ID. */
  "users.messages.batchDelete": {
    method: "POST"
    params: {
      /** The user's email address. */
      userId: string
    }
    body: GmailBatchDeleteMessagesRequest
    response: void
  }
  /** Modifies the labels and the Classification Label values on the specified messages. */
  "users.messages.batchModify": {
    method: "POST"
    params: {
      /** The user's email address. */
      userId: string
    }
    body: GmailBatchModifyMessagesRequest
    response: void
  }
  /** Immediately and permanently deletes the specified message. */
  "users.messages.delete": {
    method: "DELETE"
    params: {
      /** The ID of the message to delete. */
      id: string
      /** The user's email address. */
      userId: string
    }
    body: never
    response: void
  }
  /** Gets the specified message. */
  "users.messages.get": {
    method: "GET"
    params: {
      /** The ID of the message to retrieve. */
      id: string
      /** The format to return the message in. */
      format?: "minimal" | "full" | "raw" | "metadata"
      /** The user's email address. */
      userId: string
      /** When given and format is `METADATA`, only include headers specified. */
      metadataHeaders?: Array<string>
    }
    body: never
    response: GmailMessage
  }
  /** Imports a message into only this user's mailbox, with standard email delivery scanning and classification similar to receiving via SMTP. */
  "users.messages.import": {
    method: "POST"
    params: {
      /** Process calendar invites in the email and add any extracted meetings to the Google Calendar for this user. */
      processForCalendar?: boolean
      /** Ignore the Gmail spam classifier decision and never mark this email as SPAM in the mailbox. */
      neverMarkSpam?: boolean
      /** Source for Gmail's internal date of the message. */
      internalDateSource?: "receivedTime" | "dateHeader"
      /** The user's email address. */
      userId: string
      /** Mark the email as permanently deleted (not TRASH) and only visible in Google Vault to a Vault administrator. */
      deleted?: boolean
    }
    body: GmailMessage
    response: GmailMessage
  }
  /** Directly inserts a message into only this user's mailbox similar to `IMAP APPEND`, bypassing most scanning and classification. */
  "users.messages.insert": {
    method: "POST"
    params: {
      /** The user's email address. */
      userId: string
      /** Mark the email as permanently deleted (not TRASH) and only visible in Google Vault to a Vault administrator. */
      deleted?: boolean
      /** Source for Gmail's internal date of the message. */
      internalDateSource?: "receivedTime" | "dateHeader"
    }
    body: GmailMessage
    response: GmailMessage
  }
  /** Lists the messages in the user's mailbox. */
  "users.messages.list": {
    method: "GET"
    params: {
      /** Page token to retrieve a specific page of results in the list. */
      pageToken?: string
      /** Only return messages matching the specified query. */
      q?: string
      /** Maximum number of messages to return. */
      maxResults?: number
      /** Only return messages with labels that match all of the specified label IDs. */
      labelIds?: Array<string>
      /** Include messages from `SPAM` and `TRASH` in the results. */
      includeSpamTrash?: boolean
      /** The user's email address. */
      userId: string
    }
    body: never
    response: GmailListMessagesResponse
  }
  /** Modifies the labels and the Classification Label values on the specified message. */
  "users.messages.modify": {
    method: "POST"
    params: {
      /** The user's email address. */
      userId: string
      /** The ID of the message to modify. */
      id: string
    }
    body: GmailModifyMessageRequest
    response: GmailMessage
  }
  /** Sends the specified message to the recipients in the `To`, `Cc`, and `Bcc` headers. */
  "users.messages.send": {
    method: "POST"
    params: {
      /** The user's email address. */
      userId: string
    }
    body: GmailMessage
    response: GmailMessage
  }
  /** Moves the specified message to the trash. */
  "users.messages.trash": {
    method: "POST"
    params: {
      /** The ID of the message to Trash. */
      id: string
      /** The user's email address. */
      userId: string
    }
    body: never
    response: GmailMessage
  }
  /** Removes the specified message from the trash. */
  "users.messages.untrash": {
    method: "POST"
    params: {
      /** The ID of the message to remove from Trash. */
      id: string
      /** The user's email address. */
      userId: string
    }
    body: never
    response: GmailMessage
  }
  /** Creates and configures a client-side encryption identity that's authorized to send mail from the user account. */
  "users.settings.cse.identities.create": {
    method: "POST"
    params: {
      /** The requester's primary email address. */
      userId: string
    }
    body: GmailCseIdentity
    response: GmailCseIdentity
  }
  /** Deletes a client-side encryption identity. */
  "users.settings.cse.identities.delete": {
    method: "DELETE"
    params: {
      /** The requester's primary email address. */
      userId: string
      /** The primary email address associated with the client-side encryption identity configuration that's removed. */
      cseEmailAddress: string
    }
    body: never
    response: void
  }
  /** Retrieves a client-side encryption identity configuration. */
  "users.settings.cse.identities.get": {
    method: "GET"
    params: {
      /** The requester's primary email address. */
      userId: string
      /** The primary email address associated with the client-side encryption identity configuration that's retrieved. */
      cseEmailAddress: string
    }
    body: never
    response: GmailCseIdentity
  }
  /** Lists the client-side encrypted identities for an authenticated user. */
  "users.settings.cse.identities.list": {
    method: "GET"
    params: {
      /** The requester's primary email address. */
      userId: string
      /** The number of identities to return. */
      pageSize?: number
      /** Pagination token indicating which page of identities to return. */
      pageToken?: string
    }
    body: never
    response: GmailListCseIdentitiesResponse
  }
  /** Associates a different key pair with an existing client-side encryption identity. */
  "users.settings.cse.identities.patch": {
    method: "PATCH"
    params: {
      /** The requester's primary email address. */
      userId: string
      /** The email address of the client-side encryption identity to update. */
      emailAddress: string
    }
    body: GmailCseIdentity
    response: GmailCseIdentity
  }
  /** Creates and uploads a client-side encryption S/MIME public key certificate chain and private key metadata for the authenticated user. */
  "users.settings.cse.keypairs.create": {
    method: "POST"
    params: {
      /** The requester's primary email address. */
      userId: string
      /** The type of certificate chain validation to perform at creation. */
      chainValidation?: "all" | "none"
    }
    body: GmailCseKeyPair
    response: GmailCseKeyPair
  }
  /** Turns off a client-side encryption key pair. */
  "users.settings.cse.keypairs.disable": {
    method: "POST"
    params: {
      /** The requester's primary email address. */
      userId: string
      /** The identifier of the key pair to turn off. */
      keyPairId: string
    }
    body: GmailDisableCseKeyPairRequest
    response: GmailCseKeyPair
  }
  /** Turns on a client-side encryption key pair that was turned off. */
  "users.settings.cse.keypairs.enable": {
    method: "POST"
    params: {
      /** The requester's primary email address. */
      userId: string
      /** The identifier of the key pair to turn on. */
      keyPairId: string
    }
    body: GmailEnableCseKeyPairRequest
    response: GmailCseKeyPair
  }
  /** Retrieves an existing client-side encryption key pair. */
  "users.settings.cse.keypairs.get": {
    method: "GET"
    params: {
      /** The requester's primary email address. */
      userId: string
      /** The identifier of the key pair to retrieve. */
      keyPairId: string
    }
    body: never
    response: GmailCseKeyPair
  }
  /** Lists client-side encryption key pairs for an authenticated user. */
  "users.settings.cse.keypairs.list": {
    method: "GET"
    params: {
      /** The requester's primary email address. */
      userId: string
      /** The number of key pairs to return. */
      pageSize?: number
      /** Pagination token indicating which page of key pairs to return. */
      pageToken?: string
    }
    body: never
    response: GmailListCseKeyPairsResponse
  }
  /** Deletes a client-side encryption key pair permanently and immediately. */
  "users.settings.cse.keypairs.obliterate": {
    method: "POST"
    params: {
      /** The requester's primary email address. */
      userId: string
      /** The identifier of the key pair to obliterate. */
      keyPairId: string
    }
    body: GmailObliterateCseKeyPairRequest
    response: void
  }
  /** Adds a delegate with its verification status set directly to `accepted`, without sending any verification email. */
  "users.settings.delegates.create": {
    method: "POST"
    params: {
      /** User's email address. */
      userId: string
    }
    body: GmailDelegate
    response: GmailDelegate
  }
  /** Removes the specified delegate (which can be of any verification status), and revokes any verification that may have been required for using it. */
  "users.settings.delegates.delete": {
    method: "DELETE"
    params: {
      /** The email address of the user to be removed as a delegate. */
      delegateEmail: string
      /** User's email address. */
      userId: string
    }
    body: never
    response: void
  }
  /** Gets the specified delegate. */
  "users.settings.delegates.get": {
    method: "GET"
    params: {
      /** The email address of the user whose delegate relationship is to be retrieved. */
      delegateEmail: string
      /** User's email address. */
      userId: string
    }
    body: never
    response: GmailDelegate
  }
  /** Lists the delegates for the specified account. */
  "users.settings.delegates.list": {
    method: "GET"
    params: {
      /** User's email address. */
      userId: string
    }
    body: never
    response: GmailListDelegatesResponse
  }
  /** Creates a filter. */
  "users.settings.filters.create": {
    method: "POST"
    params: {
      /** User's email address. */
      userId: string
    }
    body: GmailFilter
    response: GmailFilter
  }
  /** Immediately and permanently deletes the specified filter. */
  "users.settings.filters.delete": {
    method: "DELETE"
    params: {
      /** The ID of the filter to be deleted. */
      id: string
      /** User's email address. */
      userId: string
    }
    body: never
    response: void
  }
  /** Gets a filter. */
  "users.settings.filters.get": {
    method: "GET"
    params: {
      /** The ID of the filter to be fetched. */
      id: string
      /** User's email address. */
      userId: string
    }
    body: never
    response: GmailFilter
  }
  /** Lists the message filters of a Gmail user. */
  "users.settings.filters.list": {
    method: "GET"
    params: {
      /** User's email address. */
      userId: string
    }
    body: never
    response: GmailListFiltersResponse
  }
  /** Creates a forwarding address. */
  "users.settings.forwardingAddresses.create": {
    method: "POST"
    params: {
      /** User's email address. */
      userId: string
    }
    body: GmailForwardingAddress
    response: GmailForwardingAddress
  }
  /** Deletes the specified forwarding address and revokes any verification that may have been required. */
  "users.settings.forwardingAddresses.delete": {
    method: "DELETE"
    params: {
      /** The forwarding address to be deleted. */
      forwardingEmail: string
      /** User's email address. */
      userId: string
    }
    body: never
    response: void
  }
  /** Gets the specified forwarding address. */
  "users.settings.forwardingAddresses.get": {
    method: "GET"
    params: {
      /** The forwarding address to be retrieved. */
      forwardingEmail: string
      /** User's email address. */
      userId: string
    }
    body: never
    response: GmailForwardingAddress
  }
  /** Lists the forwarding addresses for the specified account. */
  "users.settings.forwardingAddresses.list": {
    method: "GET"
    params: {
      /** User's email address. */
      userId: string
    }
    body: never
    response: GmailListForwardingAddressesResponse
  }
  /** Gets the auto-forwarding setting for the specified account. */
  "users.settings.getAutoForwarding": {
    method: "GET"
    params: {
      /** User's email address. */
      userId: string
    }
    body: never
    response: GmailAutoForwarding
  }
  /** Gets IMAP settings. */
  "users.settings.getImap": {
    method: "GET"
    params: {
      /** User's email address. */
      userId: string
    }
    body: never
    response: GmailImapSettings
  }
  /** Gets language settings. */
  "users.settings.getLanguage": {
    method: "GET"
    params: {
      /** User's email address. */
      userId: string
    }
    body: never
    response: GmailLanguageSettings
  }
  /** Gets POP settings. */
  "users.settings.getPop": {
    method: "GET"
    params: {
      /** User's email address. */
      userId: string
    }
    body: never
    response: GmailPopSettings
  }
  /** Gets vacation responder settings. */
  "users.settings.getVacation": {
    method: "GET"
    params: {
      /** User's email address. */
      userId: string
    }
    body: never
    response: GmailVacationSettings
  }
  /** Creates a custom "from" send-as alias. */
  "users.settings.sendAs.create": {
    method: "POST"
    params: {
      /** User's email address. */
      userId: string
    }
    body: GmailSendAs
    response: GmailSendAs
  }
  /** Deletes the specified send-as alias. */
  "users.settings.sendAs.delete": {
    method: "DELETE"
    params: {
      /** User's email address. */
      userId: string
      /** The send-as alias to be deleted. */
      sendAsEmail: string
    }
    body: never
    response: void
  }
  /** Gets the specified send-as alias. */
  "users.settings.sendAs.get": {
    method: "GET"
    params: {
      /** User's email address. */
      userId: string
      /** The send-as alias to be retrieved. */
      sendAsEmail: string
    }
    body: never
    response: GmailSendAs
  }
  /** Lists the send-as aliases for the specified account. */
  "users.settings.sendAs.list": {
    method: "GET"
    params: {
      /** User's email address. */
      userId: string
    }
    body: never
    response: GmailListSendAsResponse
  }
  /** Patch the specified send-as alias. */
  "users.settings.sendAs.patch": {
    method: "PATCH"
    params: {
      /** User's email address. */
      userId: string
      /** The send-as alias to be updated. */
      sendAsEmail: string
    }
    body: GmailSendAs
    response: GmailSendAs
  }
  /** Deletes the specified S/MIME config for the specified send-as alias. */
  "users.settings.sendAs.smimeInfo.delete": {
    method: "DELETE"
    params: {
      /** The user's email address. */
      userId: string
      /** The email address that appears in the "From:" header for mail sent using this alias. */
      sendAsEmail: string
      /** The immutable ID for the SmimeInfo. */
      id: string
    }
    body: never
    response: void
  }
  /** Gets the specified S/MIME config for the specified send-as alias. */
  "users.settings.sendAs.smimeInfo.get": {
    method: "GET"
    params: {
      /** The immutable ID for the SmimeInfo. */
      id: string
      /** The user's email address. */
      userId: string
      /** The email address that appears in the "From:" header for mail sent using this alias. */
      sendAsEmail: string
    }
    body: never
    response: GmailSmimeInfo
  }
  /** Insert (upload) the given S/MIME config for the specified send-as alias. */
  "users.settings.sendAs.smimeInfo.insert": {
    method: "POST"
    params: {
      /** The user's email address. */
      userId: string
      /** The email address that appears in the "From:" header for mail sent using this alias. */
      sendAsEmail: string
    }
    body: GmailSmimeInfo
    response: GmailSmimeInfo
  }
  /** Lists S/MIME configs for the specified send-as alias. */
  "users.settings.sendAs.smimeInfo.list": {
    method: "GET"
    params: {
      /** The user's email address. */
      userId: string
      /** The email address that appears in the "From:" header for mail sent using this alias. */
      sendAsEmail: string
    }
    body: never
    response: GmailListSmimeInfoResponse
  }
  /** Sets the default S/MIME config for the specified send-as alias. */
  "users.settings.sendAs.smimeInfo.setDefault": {
    method: "POST"
    params: {
      /** The user's email address. */
      userId: string
      /** The email address that appears in the "From:" header for mail sent using this alias. */
      sendAsEmail: string
      /** The immutable ID for the SmimeInfo. */
      id: string
    }
    body: never
    response: void
  }
  /** Updates a send-as alias. */
  "users.settings.sendAs.update": {
    method: "PUT"
    params: {
      /** User's email address. */
      userId: string
      /** The send-as alias to be updated. */
      sendAsEmail: string
    }
    body: GmailSendAs
    response: GmailSendAs
  }
  /** Sends a verification email to the specified send-as alias address. */
  "users.settings.sendAs.verify": {
    method: "POST"
    params: {
      /** User's email address. */
      userId: string
      /** The send-as alias to be verified. */
      sendAsEmail: string
    }
    body: never
    response: void
  }
  /** Updates the auto-forwarding setting for the specified account. */
  "users.settings.updateAutoForwarding": {
    method: "PUT"
    params: {
      /** User's email address. */
      userId: string
    }
    body: GmailAutoForwarding
    response: GmailAutoForwarding
  }
  /** Updates IMAP settings. */
  "users.settings.updateImap": {
    method: "PUT"
    params: {
      /** User's email address. */
      userId: string
    }
    body: GmailImapSettings
    response: GmailImapSettings
  }
  /** Updates language settings. */
  "users.settings.updateLanguage": {
    method: "PUT"
    params: {
      /** User's email address. */
      userId: string
    }
    body: GmailLanguageSettings
    response: GmailLanguageSettings
  }
  /** Updates POP settings. */
  "users.settings.updatePop": {
    method: "PUT"
    params: {
      /** User's email address. */
      userId: string
    }
    body: GmailPopSettings
    response: GmailPopSettings
  }
  /** Updates vacation responder settings. */
  "users.settings.updateVacation": {
    method: "PUT"
    params: {
      /** User's email address. */
      userId: string
    }
    body: GmailVacationSettings
    response: GmailVacationSettings
  }
  /** Turn off push notification delivery for the given user mailbox. */
  "users.stop": {
    method: "POST"
    params: {
      /** The user's email address. */
      userId: string
    }
    body: never
    response: void
  }
  /** Immediately and permanently deletes the specified thread. */
  "users.threads.delete": {
    method: "DELETE"
    params: {
      /** ID of the Thread to delete. */
      id: string
      /** The user's email address. */
      userId: string
    }
    body: never
    response: void
  }
  /** Gets the specified thread. */
  "users.threads.get": {
    method: "GET"
    params: {
      /** The user's email address. */
      userId: string
      /** When given and format is METADATA, only include headers specified. */
      metadataHeaders?: Array<string>
      /** The ID of the thread to retrieve. */
      id: string
      /** The format to return the messages in. */
      format?: "full" | "metadata" | "minimal"
    }
    body: never
    response: GmailThread
  }
  /** Lists the threads in the user's mailbox. */
  "users.threads.list": {
    method: "GET"
    params: {
      /** Only return threads with labels that match all of the specified label IDs. */
      labelIds?: Array<string>
      /** Include threads from `SPAM` and `TRASH` in the results. */
      includeSpamTrash?: boolean
      /** Maximum number of threads to return. */
      maxResults?: number
      /** The user's email address. */
      userId: string
      /** Page token to retrieve a specific page of results in the list. */
      pageToken?: string
      /** Only return threads matching the specified query. */
      q?: string
    }
    body: never
    response: GmailListThreadsResponse
  }
  /** Modifies the labels applied to the thread. */
  "users.threads.modify": {
    method: "POST"
    params: {
      /** The ID of the thread to modify. */
      id: string
      /** The user's email address. */
      userId: string
    }
    body: GmailModifyThreadRequest
    response: GmailThread
  }
  /** Moves the specified thread to the trash. */
  "users.threads.trash": {
    method: "POST"
    params: {
      /** The user's email address. */
      userId: string
      /** The ID of the thread to Trash. */
      id: string
    }
    body: never
    response: GmailThread
  }
  /** Removes the specified thread from the trash. */
  "users.threads.untrash": {
    method: "POST"
    params: {
      /** The user's email address. */
      userId: string
      /** The ID of the thread to remove from Trash. */
      id: string
    }
    body: never
    response: GmailThread
  }
  /** Set up or update a push notification watch on the given user mailbox. */
  "users.watch": {
    method: "POST"
    params: {
      /** The user's email address. */
      userId: string
    }
    body: GmailWatchRequest
    response: GmailWatchResponse
  }
}

/** HTTP method, path template, and whether the method accepts a JSON request body. */
export const gmailMethods = {
  "users.drafts.create": ["POST", "gmail/v1/users/{userId}/drafts", true],
  "users.drafts.delete": ["DELETE", "gmail/v1/users/{userId}/drafts/{id}", false],
  "users.drafts.get": ["GET", "gmail/v1/users/{userId}/drafts/{id}", false],
  "users.drafts.list": ["GET", "gmail/v1/users/{userId}/drafts", false],
  "users.drafts.send": ["POST", "gmail/v1/users/{userId}/drafts/send", true],
  "users.drafts.update": ["PUT", "gmail/v1/users/{userId}/drafts/{id}", true],
  "users.getProfile": ["GET", "gmail/v1/users/{userId}/profile", false],
  "users.history.list": ["GET", "gmail/v1/users/{userId}/history", false],
  "users.labels.create": ["POST", "gmail/v1/users/{userId}/labels", true],
  "users.labels.delete": ["DELETE", "gmail/v1/users/{userId}/labels/{id}", false],
  "users.labels.get": ["GET", "gmail/v1/users/{userId}/labels/{id}", false],
  "users.labels.list": ["GET", "gmail/v1/users/{userId}/labels", false],
  "users.labels.patch": ["PATCH", "gmail/v1/users/{userId}/labels/{id}", true],
  "users.labels.update": ["PUT", "gmail/v1/users/{userId}/labels/{id}", true],
  "users.messages.attachments.get": ["GET", "gmail/v1/users/{userId}/messages/{messageId}/attachments/{id}", false],
  "users.messages.batchDelete": ["POST", "gmail/v1/users/{userId}/messages/batchDelete", true],
  "users.messages.batchModify": ["POST", "gmail/v1/users/{userId}/messages/batchModify", true],
  "users.messages.delete": ["DELETE", "gmail/v1/users/{userId}/messages/{id}", false],
  "users.messages.get": ["GET", "gmail/v1/users/{userId}/messages/{id}", false],
  "users.messages.import": ["POST", "gmail/v1/users/{userId}/messages/import", true],
  "users.messages.insert": ["POST", "gmail/v1/users/{userId}/messages", true],
  "users.messages.list": ["GET", "gmail/v1/users/{userId}/messages", false],
  "users.messages.modify": ["POST", "gmail/v1/users/{userId}/messages/{id}/modify", true],
  "users.messages.send": ["POST", "gmail/v1/users/{userId}/messages/send", true],
  "users.messages.trash": ["POST", "gmail/v1/users/{userId}/messages/{id}/trash", false],
  "users.messages.untrash": ["POST", "gmail/v1/users/{userId}/messages/{id}/untrash", false],
  "users.settings.cse.identities.create": ["POST", "gmail/v1/users/{userId}/settings/cse/identities", true],
  "users.settings.cse.identities.delete": ["DELETE", "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}", false],
  "users.settings.cse.identities.get": ["GET", "gmail/v1/users/{userId}/settings/cse/identities/{cseEmailAddress}", false],
  "users.settings.cse.identities.list": ["GET", "gmail/v1/users/{userId}/settings/cse/identities", false],
  "users.settings.cse.identities.patch": ["PATCH", "gmail/v1/users/{userId}/settings/cse/identities/{emailAddress}", true],
  "users.settings.cse.keypairs.create": ["POST", "gmail/v1/users/{userId}/settings/cse/keypairs", true],
  "users.settings.cse.keypairs.disable": ["POST", "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:disable", true],
  "users.settings.cse.keypairs.enable": ["POST", "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:enable", true],
  "users.settings.cse.keypairs.get": ["GET", "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}", false],
  "users.settings.cse.keypairs.list": ["GET", "gmail/v1/users/{userId}/settings/cse/keypairs", false],
  "users.settings.cse.keypairs.obliterate": ["POST", "gmail/v1/users/{userId}/settings/cse/keypairs/{keyPairId}:obliterate", true],
  "users.settings.delegates.create": ["POST", "gmail/v1/users/{userId}/settings/delegates", true],
  "users.settings.delegates.delete": ["DELETE", "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}", false],
  "users.settings.delegates.get": ["GET", "gmail/v1/users/{userId}/settings/delegates/{delegateEmail}", false],
  "users.settings.delegates.list": ["GET", "gmail/v1/users/{userId}/settings/delegates", false],
  "users.settings.filters.create": ["POST", "gmail/v1/users/{userId}/settings/filters", true],
  "users.settings.filters.delete": ["DELETE", "gmail/v1/users/{userId}/settings/filters/{id}", false],
  "users.settings.filters.get": ["GET", "gmail/v1/users/{userId}/settings/filters/{id}", false],
  "users.settings.filters.list": ["GET", "gmail/v1/users/{userId}/settings/filters", false],
  "users.settings.forwardingAddresses.create": ["POST", "gmail/v1/users/{userId}/settings/forwardingAddresses", true],
  "users.settings.forwardingAddresses.delete": ["DELETE", "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}", false],
  "users.settings.forwardingAddresses.get": ["GET", "gmail/v1/users/{userId}/settings/forwardingAddresses/{forwardingEmail}", false],
  "users.settings.forwardingAddresses.list": ["GET", "gmail/v1/users/{userId}/settings/forwardingAddresses", false],
  "users.settings.getAutoForwarding": ["GET", "gmail/v1/users/{userId}/settings/autoForwarding", false],
  "users.settings.getImap": ["GET", "gmail/v1/users/{userId}/settings/imap", false],
  "users.settings.getLanguage": ["GET", "gmail/v1/users/{userId}/settings/language", false],
  "users.settings.getPop": ["GET", "gmail/v1/users/{userId}/settings/pop", false],
  "users.settings.getVacation": ["GET", "gmail/v1/users/{userId}/settings/vacation", false],
  "users.settings.sendAs.create": ["POST", "gmail/v1/users/{userId}/settings/sendAs", true],
  "users.settings.sendAs.delete": ["DELETE", "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}", false],
  "users.settings.sendAs.get": ["GET", "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}", false],
  "users.settings.sendAs.list": ["GET", "gmail/v1/users/{userId}/settings/sendAs", false],
  "users.settings.sendAs.patch": ["PATCH", "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}", true],
  "users.settings.sendAs.smimeInfo.delete": ["DELETE", "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}", false],
  "users.settings.sendAs.smimeInfo.get": ["GET", "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}", false],
  "users.settings.sendAs.smimeInfo.insert": ["POST", "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo", true],
  "users.settings.sendAs.smimeInfo.list": ["GET", "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo", false],
  "users.settings.sendAs.smimeInfo.setDefault": ["POST", "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/smimeInfo/{id}/setDefault", false],
  "users.settings.sendAs.update": ["PUT", "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}", true],
  "users.settings.sendAs.verify": ["POST", "gmail/v1/users/{userId}/settings/sendAs/{sendAsEmail}/verify", false],
  "users.settings.updateAutoForwarding": ["PUT", "gmail/v1/users/{userId}/settings/autoForwarding", true],
  "users.settings.updateImap": ["PUT", "gmail/v1/users/{userId}/settings/imap", true],
  "users.settings.updateLanguage": ["PUT", "gmail/v1/users/{userId}/settings/language", true],
  "users.settings.updatePop": ["PUT", "gmail/v1/users/{userId}/settings/pop", true],
  "users.settings.updateVacation": ["PUT", "gmail/v1/users/{userId}/settings/vacation", true],
  "users.stop": ["POST", "gmail/v1/users/{userId}/stop", false],
  "users.threads.delete": ["DELETE", "gmail/v1/users/{userId}/threads/{id}", false],
  "users.threads.get": ["GET", "gmail/v1/users/{userId}/threads/{id}", false],
  "users.threads.list": ["GET", "gmail/v1/users/{userId}/threads", false],
  "users.threads.modify": ["POST", "gmail/v1/users/{userId}/threads/{id}/modify", true],
  "users.threads.trash": ["POST", "gmail/v1/users/{userId}/threads/{id}/trash", false],
  "users.threads.untrash": ["POST", "gmail/v1/users/{userId}/threads/{id}/untrash", false],
  "users.watch": ["POST", "gmail/v1/users/{userId}/watch", true],
} as const

export const gmailRootUrl = "https://gmail.googleapis.com/"
