import { readdir, readFile } from "node:fs/promises";
import { join, resolve } from "node:path";

import { expect, it } from "vitest";

const sourceRoot = resolve(import.meta.dirname, "../src");
const iconPattern = /\bi-(lucide|ph)-([a-z0-9]+(?:-[a-z0-9]+)*)/g;

async function sourceIcons(root: string): Promise<string[]> {
  const icons = new Set<string>();
  for (const entry of await readdir(root, { recursive: true, withFileTypes: true })) {
    if (!entry.isFile() || !/\.(?:ts|vue)$/.test(entry.name)) continue;
    const source = await readFile(join(entry.parentPath, entry.name), "utf8");
    for (const [, collection, name] of source.matchAll(iconPattern)) icons.add(`${collection}:${name}`);
  }
  return [...icons].sort();
}

it("lists every icon that the UI sources use", async () => {
  const icons = await sourceIcons(sourceRoot);
  expect(icons.length).toBeGreaterThan(0);
  await expect([
    "// Generated by test/icons.test.ts from the UI sources.",
    "// Run `vp test test/icons.test.ts -u` in packages/ui after you add or remove a UI icon.",
    "export const viteHubUIIcons: readonly string[] = [",
    ...icons.map((icon) => `  "${icon}",`),
    "];",
    "",
  ].join("\n")).toMatchFileSnapshot("../src/icons.ts");
});
