import { defineDiagnostics } from "nostics"

const dynamicError = {
  why: ({ message }: { message?: unknown }) => message === undefined ? "" : String(message),
}

// Each code identifies one ViteHub failure site. Keep published codes stable.
export const internalErrorDiagnostics = /*#__PURE__*/ defineDiagnostics({
  docsBase: () => "https://vitehub.dev/docs/reference/errors-diagnostics",
  codes: {
    INTERNAL_R0012: dynamicError,
    INTERNAL_R0013: dynamicError,
    INTERNAL_B0001: dynamicError,
    INTERNAL_B0002: dynamicError,
    INTERNAL_B0003: dynamicError,
    INTERNAL_B0004: dynamicError,
    INTERNAL_B0005: dynamicError,
    INTERNAL_B0006: dynamicError,
    INTERNAL_B0007: dynamicError,
    INTERNAL_B0008: dynamicError,
    INTERNAL_B0009: dynamicError,
    INTERNAL_B0010: dynamicError,
    INTERNAL_B0011: dynamicError,
    INTERNAL_B0012: dynamicError,
    INTERNAL_B0013: dynamicError,
    INTERNAL_B0014: dynamicError,
    INTERNAL_B0015: dynamicError,
    INTERNAL_B0016: dynamicError,
    INTERNAL_B0017: dynamicError,
    INTERNAL_B0018: dynamicError,
    INTERNAL_B0019: dynamicError,
    INTERNAL_B0020: dynamicError,
    INTERNAL_B0021: dynamicError,
    INTERNAL_B0022: dynamicError,
    INTERNAL_B0023: dynamicError,
    INTERNAL_B0024: dynamicError,
    INTERNAL_B0025: dynamicError,
    INTERNAL_B0026: dynamicError,
    INTERNAL_B0027: dynamicError,
    INTERNAL_B0028: dynamicError,
    INTERNAL_B0029: dynamicError,
    INTERNAL_B0030: dynamicError,
    INTERNAL_B0031: dynamicError,
    INTERNAL_B0032: dynamicError,
    INTERNAL_B0033: dynamicError,
    INTERNAL_B0034: dynamicError,
    INTERNAL_B0035: dynamicError,
    INTERNAL_B0036: dynamicError,
    INTERNAL_B0037: dynamicError,
    INTERNAL_B0038: dynamicError,
    INTERNAL_B0039: dynamicError,
    INTERNAL_B0040: dynamicError,
    INTERNAL_B0041: dynamicError,
    INTERNAL_B0042: dynamicError,
    INTERNAL_B0043: dynamicError,
    INTERNAL_B0044: dynamicError,
    INTERNAL_B0045: dynamicError,
    INTERNAL_B0046: dynamicError,
    INTERNAL_B0047: dynamicError,
    INTERNAL_C0001: dynamicError,
    INTERNAL_C0002: dynamicError,
    INTERNAL_R0001: dynamicError,
    INTERNAL_R0002: dynamicError,
    INTERNAL_R0003: dynamicError,
    INTERNAL_R0004: dynamicError,
    INTERNAL_R0005: dynamicError,
    INTERNAL_R0006: dynamicError,
    INTERNAL_R0007: dynamicError,
    INTERNAL_R0008: dynamicError,
    INTERNAL_R0009: dynamicError,
    INTERNAL_R0010: dynamicError,
    INTERNAL_R0011: dynamicError,
  },
})
