import { defineNuxtConfig } from "nuxt/config";
import { fileURLToPath } from "node:url";

export default defineNuxtConfig({
  extends: ["docus"],
  modules: ["./modules/vitehub-docs"],
  site: {
    name: "ViteHub",
    url: "https://vitehub.dev",
  },
  llms: { domain: "https://vitehub.dev" },
  app: {
    head: {
      link: [
        { rel: "icon", type: "image/png", href: "/favicon.png" },
        { rel: "apple-touch-icon", sizes: "180x180", href: "/apple-touch-icon.png" },
      ],
    },
  },
  css: ["~/assets/main.css"],
  vite: {
    resolve: {
      alias: {
        debug: fileURLToPath(new URL("./app/shims/debug.ts", import.meta.url)),
        extend: fileURLToPath(new URL("./app/shims/extend.ts", import.meta.url)),
      },
    },
  },
  icon: {
    provider: "server",
    fallbackToApi: false,
    customCollections: [
      {
        prefix: "unjs",
        dir: fileURLToPath(new URL("./app/assets/icons/unjs", import.meta.url)),
      },
    ],
    serverBundle: {
      collections: ["lucide", "ph", "simple-icons", "vscode-icons"],
    },
    clientBundle: {
      scan: true,
      icons: [
        "lucide:brain",
        "lucide:chevron-down",
        "lucide:chevron-right",
        "lucide:hash",
        "lucide:lightbulb",
        "lucide:menu",
        "lucide:moon",
        "lucide:search",
        "lucide:sun",
        "lucide:terminal",
        "lucide:text-align-start",
        "ph:activity-light",
        "ph:arrows-split-light",
        "ph:book-bookmark-light",
        "ph:book-open-light",
        "ph:brain-light",
        "ph:broadcast-light",
        "ph:browser-light",
        "ph:calendar-check-light",
        "ph:caret-down-light",
        "ph:chart-bar-light",
        "ph:chat-circle-text-light",
        "ph:chat-text-light",
        "ph:chats-circle-light",
        "ph:clipboard-text-light",
        "ph:cloud-arrow-up-light",
        "ph:cloud-light",
        "ph:code-light",
        "ph:cpu-light",
        "ph:cube-light",
        "ph:database-light",
        "ph:door-open-light",
        "ph:download-simple-light",
        "ph:file-code-light",
        "ph:file-light",
        "ph:file-magnifying-glass-light",
        "ph:file-text-light",
        "ph:files-light",
        "ph:folder-light",
        "ph:folder-notch-open-light",
        "ph:folder-plus-light",
        "ph:gauge-light",
        "ph:git-branch-light",
        "ph:git-pull-request-light",
        "ph:hard-drives-light",
        "ph:identification-card-light",
        "ph:key-light",
        "ph:lightning-light",
        "ph:list-checks-light",
        "ph:list-numbers-light",
        "ph:magnifying-glass-light",
        "ph:map-trifold-light",
        "ph:markdown-logo-light",
        "ph:package-light",
        "ph:paper-plane-tilt-light",
        "ph:path-light",
        "ph:play-circle-light",
        "ph:plug-light",
        "ph:robot-light",
        "ph:rocket-launch-light",
        "ph:scroll-light",
        "ph:seal-check-light",
        "ph:shield-check-light",
        "ph:shield-warning-light",
        "ph:sliders-horizontal-light",
        "ph:squares-four-light",
        "ph:stethoscope-light",
        "ph:terminal-light",
        "ph:terminal-window-light",
        "ph:text-h-light",
        "ph:tree-structure-light",
        "ph:triangle-light",
        "ph:user-check-light",
        "ph:users-three-light",
        "ph:warning-circle-light",
        "ph:waveform-light",
        "ph:wrench-light",
        "simple-icons:cloudflare",
        "simple-icons:discord",
        "simple-icons:vercel",
        "vscode-icons:file-type-typescript",
      ],
    },
  },
  devtools: {
    enabled: false,
  },
  nitro: {
    preset: "cloudflare_module",
    cloudflare: {
      nodeCompat: true,
    },
    prerender: {
      failOnError: true,
    },
  },
  future: {
    compatibilityVersion: 4,
  },
  compatibilityDate: "2026-05-30",
  experimental: {
    payloadExtraction: false,
    defaults: {
      nuxtLink: {
        trailingSlash: "append",
      },
    },
  },
});
