name: pkg.pr.new

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"
  workflow_dispatch:

concurrency:
  group: pkg-pr-new-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: publish preview packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/setup

      - run: pnpm -r --filter './packages/*' --if-present run build

      - name: Publish preview packages
        run: pnpm dlx pkg-pr-new publish './packages/*' --pnpm --packageManager=pnpm
