name: pkg.pr.new

on:
  push:
    branches:
      - "**"
    tags:
      - "!**"
  workflow_dispatch:

concurrency:
  group: pkg-pr-new-${{ github.ref }}
  cancel-in-progress: true

jobs:
  publish:
    name: publish preview packages
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - uses: ./.github/actions/setup

      - run: vp run build

      - name: Publish preview packages
        run: vp dlx pkg-pr-new publish './packages/*' --pnpm --packageManager=pnpm
